C     Diagram 1
      DATA MAPCONFIG(1)/1/
      DATA TSTRATEGY(1)/1/
      DATA (IFOREST(I,-1,1),I=1,2)/2,5/
      DATA TPRID(-1,1)/22/
      DATA (SPROP(I,-1,1),I=1,1)/0/
      DATA (IFOREST(I,-2,1),I=1,2)/-1,4/
      DATA TPRID(-2,1)/6/
      DATA (SPROP(I,-2,1),I=1,1)/0/
      DATA (IFOREST(I,-3,1),I=1,2)/-2,3/
      DATA TPRID(-3,1)/21/
      DATA (SPROP(I,-3,1),I=1,1)/0/
C     Diagram 2
      DATA MAPCONFIG(2)/2/
      DATA TSTRATEGY(2)/1/
      DATA (IFOREST(I,-1,2),I=1,2)/2,5/
      DATA TPRID(-1,2)/22/
      DATA (SPROP(I,-1,2),I=1,1)/0/
      DATA (IFOREST(I,-2,2),I=1,2)/-1,3/
      DATA TPRID(-2,2)/6/
      DATA (SPROP(I,-2,2),I=1,1)/0/
      DATA (IFOREST(I,-3,2),I=1,2)/-2,4/
      DATA TPRID(-3,2)/21/
      DATA (SPROP(I,-3,2),I=1,1)/0/
C     Number of configs
      DATA MAPCONFIG(0)/2/
C     used fake id
      DATA FAKE_ID/7/
