ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of sm-full'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_40 = ', GC_40
      WRITE(*,2) 'GC_106 = ', GC_106
      WRITE(*,2) 'GC_107 = ', GC_107
      WRITE(*,2) 'GC_108 = ', GC_108
