ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of loop_sm-full'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_4 = ', GC_4
      WRITE(*,2) 'GC_5 = ', GC_5
      WRITE(*,2) 'R2_GQQ = ', R2_GQQ
      WRITE(*,2) 'R2_QQq = ', R2_QQQ
      WRITE(*,2) 'R2_QQt = ', R2_QQT
      WRITE(*,2) 'UV_GQQg_1eps = ', UV_GQQG_1EPS
      WRITE(*,2) 'UV_GQQq_1eps = ', UV_GQQQ_1EPS
      WRITE(*,2) 'UV_GQQc_1eps = ', UV_GQQC_1EPS
      WRITE(*,2) 'UV_GQQb_1eps = ', UV_GQQB_1EPS
      WRITE(*,2) 'UV_GQQt_1eps = ', UV_GQQT_1EPS
      WRITE(*,2) 'UV_tMass_1eps = ', UV_TMASS_1EPS
      WRITE(*,2) 'UVWfct_t_0_1eps = ', UVWFCT_T_0_1EPS
      WRITE(*,2) 'UVWfct_G_0_1eps = ', UVWFCT_G_0_1EPS
      WRITE(*,2) 'UVWfct_G_1_1eps = ', UVWFCT_G_1_1EPS
      WRITE(*,2) 'UVWfct_G_2_1eps = ', UVWFCT_G_2_1EPS
      WRITE(*,2) 'R2_UUA = ', R2_UUA
      WRITE(*,2) 'R2_UUZ_V2 = ', R2_UUZ_V2
      WRITE(*,2) 'R2_UUZ_V5 = ', R2_UUZ_V5
      WRITE(*,2) 'R2_ttH = ', R2_TTH
      WRITE(*,2) 'R2_GGHc = ', R2_GGHC
      WRITE(*,2) 'R2_GGHb = ', R2_GGHB
      WRITE(*,2) 'R2_GGHt = ', R2_GGHT
      WRITE(*,2) 'R2_GGZup = ', R2_GGZUP
      WRITE(*,2) 'R2_GGZdown = ', R2_GGZDOWN
      WRITE(*,2) 'UV_Htt_1eps = ', UV_HTT_1EPS
      WRITE(*,2) 'UV_GQQc = ', UV_GQQC
      WRITE(*,2) 'UV_GQQb = ', UV_GQQB
      WRITE(*,2) 'UV_GQQt = ', UV_GQQT
      WRITE(*,2) 'UV_tMass = ', UV_TMASS
      WRITE(*,2) 'UVWfct_t_0 = ', UVWFCT_T_0
      WRITE(*,2) 'UVWfct_G_0 = ', UVWFCT_G_0
      WRITE(*,2) 'UVWfct_G_1 = ', UVWFCT_G_1
      WRITE(*,2) 'UVWfct_G_2 = ', UVWFCT_G_2
      WRITE(*,2) 'UV_Htt = ', UV_HTT
      WRITE(*,2) 'GC_1 = ', GC_1
      WRITE(*,2) 'GC_2 = ', GC_2
      WRITE(*,2) 'GC_3 = ', GC_3
      WRITE(*,2) 'GC_21 = ', GC_21
      WRITE(*,2) 'GC_22 = ', GC_22
      WRITE(*,2) 'GC_23 = ', GC_23
      WRITE(*,2) 'GC_24 = ', GC_24
      WRITE(*,2) 'GC_33 = ', GC_33
      WRITE(*,2) 'GC_34 = ', GC_34
      WRITE(*,2) 'GC_36 = ', GC_36
      WRITE(*,2) 'GC_37 = ', GC_37
