ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of sm-full'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_40 = ', GC_40
      WRITE(*,2) 'GC_47 = ', GC_47
      WRITE(*,2) 'GC_48 = ', GC_48
      WRITE(*,2) 'GC_49 = ', GC_49
