      DOUBLE PRECISION FUNCTION DSIG2(PP,WGT,IMODE)
C     ****************************************************
C     
C     Generated by MadGraph5_aMC@NLO v. 3.6.6, 2025-10-30
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     Process: g e- > e- t t~ WEIGHTED<=5 @2
C     *   Decay: t > b w+ WEIGHTED<=2
C     *     Decay: w+ > s~ c WEIGHTED<=2
C     *   Decay: t~ > b~ w- WEIGHTED<=2
C     *     Decay: w- > mu- vm~ WEIGHTED<=2
C     
C     RETURNS DIFFERENTIAL CROSS SECTION
C     Input:
C     pp    4 momentum of external particles
C     wgt   weight from Monte Carlo
C     imode 0 run, 1 init, 2 reweight, 
C     3 finalize, 4 only PDFs,
C     5 squared amplitude only (never
C     generate events)
C     Output:
C     Amplitude squared and summed
C     ****************************************************
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INCLUDE 'genps.inc'
      INCLUDE 'nexternal.inc'
      INCLUDE 'maxconfigs.inc'
      INCLUDE 'maxamps.inc'
      DOUBLE PRECISION       CONV
      PARAMETER (CONV=389379.66*1000)  !CONV TO PICOBARNS
      REAL*8     PI
      PARAMETER (PI=3.1415926D0)
C     
C     ARGUMENTS 
C     
      DOUBLE PRECISION PP(0:3,NEXTERNAL), WGT
      INTEGER IMODE
C     
C     LOCAL VARIABLES 
C     
      INTEGER I,ITYPE,LP,IPROC
      DOUBLE PRECISION QSCALE
      DOUBLE PRECISION G1
      DOUBLE PRECISION EM2
      DOUBLE PRECISION XPQ(-7:7),PD(0:MAXPROC)
      DOUBLE PRECISION DSIGUU,R,RCONF

      INTEGER LUN,ICONF,IFACT,NFACT
      DATA NFACT/1/
      SAVE NFACT
C     
C     STUFF FOR DRESSED EE COLLISIONS
C     
      INCLUDE '../../Source/PDF/eepdf.inc'
      DOUBLE PRECISION EE_COMP_PROD

      INTEGER I_EE
C     
C     STUFF FOR UPC
C     
      DOUBLE PRECISION PHOTONPDFSQUARE
C     
C     EXTERNAL FUNCTIONS
C     
      LOGICAL PASSCUTS
      DOUBLE PRECISION ALPHAS2,REWGT,PDG2PDF,CUSTOM_BIAS
      INTEGER NEXTUNOPEN
C     
C     GLOBAL VARIABLES
C     
      INTEGER          IPSEL
      COMMON /SUBPROC/ IPSEL
C     MINCFIG has this config number
      INTEGER           MINCFIG, MAXCFIG
      COMMON/TO_CONFIGS/MINCFIG, MAXCFIG
      INTEGER MAPCONFIG(0:LMAXCONFIGS), ICONFIG
      COMMON/TO_MCONFIGS/MAPCONFIG, ICONFIG
C     Keep track of whether cuts already calculated for this event
      LOGICAL CUTSDONE,CUTSPASSED
      COMMON/TO_CUTSDONE/CUTSDONE,CUTSPASSED

      INTEGER SUBDIAG(MAXSPROC),IB(2)
      COMMON/TO_SUB_DIAG/SUBDIAG,IB
      INCLUDE '../../Source/vector.inc'  ! defines VECSIZE_MEMMAX
      INCLUDE 'run.inc'
      INCLUDE '../../Source/PDF/pdf.inc'
C     Common blocks
      DOUBLE PRECISION RHEL, RCOL
      INTEGER SELECTED_HEL(VECSIZE_MEMMAX)
      INTEGER SELECTED_COL(VECSIZE_MEMMAX)
C     
C     local
C     
      DOUBLE PRECISION P1(0:3, NEXTERNAL)
      INTEGER CHANNEL
C     
C     DATA
C     
      DATA G1/1*1D0/
      DATA EM2/1*1D0/
C     ----------
C     BEGIN CODE
C     ----------
      SELECTED_HEL(:) = 0
      SELECTED_COL(:) = 0
      DSIG2=0D0

      IF(IMODE.EQ.1)THEN
C       Set up process information from file symfact
        LUN=NEXTUNOPEN()
        NFACT=1
        OPEN(UNIT=LUN,FILE='../symfact.dat',STATUS='OLD',ERR=20)
        DO WHILE(.TRUE.)
          READ(LUN,*,ERR=10,END=10) RCONF, IFACT
          ICONF=INT(RCONF)
          IF(ICONF.EQ.MAPCONFIG(MINCFIG))THEN
            NFACT=IFACT
          ENDIF
        ENDDO
        DSIG2 = NFACT
 10     CLOSE(LUN)
        RETURN
 20     WRITE(*,*)'Error opening symfact.dat. No symmetry factor used.'
        RETURN
      ENDIF
C     Continue only if IMODE is 0, 4 or 5
      IF(IMODE.NE.0.AND.IMODE.NE.4.AND.IMODE.NE.5) RETURN


      IF (ABS(LPP(IB(1))).GE.1) THEN
C       LP=SIGN(1,LPP(IB(1)))
        IF (DSQRT(Q2FACT(IB(1))).EQ.0D0) THEN
          QSCALE=0D0
          DO I=3,NEXTERNAL
            QSCALE=QSCALE+DSQRT(MAX(0D0,(PP(0,I)+PP(3,I))*(PP(0,I)
     $       -PP(3,I))))
          ENDDO
          QSCALE=QSCALE/2D0
        ELSE
          QSCALE=DSQRT(Q2FACT(1))
        ENDIF
        G1=PDG2PDF(LPP(IB(1)),0, IB(1),XBK(IB(1)), QSCALE)
      ENDIF
      IF (ABS(LPP(IB(2))).GE.1) THEN
C       LP=SIGN(1,LPP(IB(2)))
        IF (DSQRT(Q2FACT(IB(2))).NE.0D0) THEN
          QSCALE=DSQRT(Q2FACT(2))
        ENDIF
        EM2=PDG2PDF(LPP(IB(2)),11, IB(2),XBK(IB(2)), QSCALE)
      ENDIF
      PD(0) = 0D0
      IPROC = 0
      IPROC=IPROC+1  ! g e- > e- b s~ c b~ mu- vm~
      PD(IPROC)=G1*EM2
      PD(0)=PD(0)+DABS(PD(IPROC))
      IF (IMODE.EQ.4)THEN
        DSIG2 = PD(0)
        RETURN
      ENDIF
      IF(FRAME_ID.NE.6)THEN
        CALL BOOST_TO_FRAME(PP, FRAME_ID, P1)
      ELSE
        P1 = PP
      ENDIF

      CHANNEL = SUBDIAG(2)
      CALL RANMAR(RHEL)
      CALL RANMAR(RCOL)
      CALL SMATRIX2(P1,RHEL, RCOL,CHANNEL,1, DSIGUU, SELECTED_HEL(1),
     $  SELECTED_COL(1))


      IF (IMODE.EQ.5) THEN
        IF (DSIGUU.LT.1D199) THEN
          DSIG2 = DSIGUU*CONV
        ELSE
          DSIG2 = 0.0D0
        ENDIF
        RETURN
      ENDIF
C     Select a flavor combination (need to do here for right sign)
      CALL RANMAR(R)
      IPSEL=0
      DO WHILE (R.GE.0D0 .AND. IPSEL.LT.IPROC)
        IPSEL=IPSEL+1
        R=R-DABS(PD(IPSEL))/PD(0)
      ENDDO

      DSIGUU=DSIGUU*REWGT(PP,1)

C     Apply the bias weight specified in the run card (default is 1.0)
      DSIGUU=DSIGUU*CUSTOM_BIAS(PP,DSIGUU,2,1)

      DSIGUU=DSIGUU*NFACT

      IF (DSIGUU.LT.1D199) THEN
C       Set sign of dsig based on sign of PDF and matrix element
        DSIG2=DSIGN(CONV*PD(0)*DSIGUU,DSIGUU*PD(IPSEL))
      ELSE
        WRITE(*,*) 'Error in matrix element'
        DSIGUU=0D0
        DSIG2=0D0
      ENDIF
C     Generate events only if IMODE is 0.
      IF(IMODE.EQ.0.AND.DABS(DSIG2).GT.0D0)THEN
C       Call UNWGT to unweight and store events
        CALL UNWGT(PP,DSIG2*WGT,2,SELECTED_HEL(1), SELECTED_COL(1), 1)
      ENDIF

      END
C     
C     Functionality to handling grid
C     



      DOUBLE PRECISION FUNCTION DSIG2_VEC(ALL_PP, ALL_XBK, ALL_Q2FACT,
     $  ALL_CM_RAP, ALL_WGT, IMODE, ALL_OUT, SYMCONF, CONFSUB,
     $  ICONF_VEC, IMIRROR_VEC, VECSIZE_USED)
C     ****************************************************
C     
C     Generated by MadGraph5_aMC@NLO v. 3.6.6, 2025-10-30
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     Process: g e- > e- t t~ WEIGHTED<=5 @2
C     *   Decay: t > b w+ WEIGHTED<=2
C     *     Decay: w+ > s~ c WEIGHTED<=2
C     *   Decay: t~ > b~ w- WEIGHTED<=2
C     *     Decay: w- > mu- vm~ WEIGHTED<=2
C     
C     RETURNS DIFFERENTIAL CROSS SECTION
C     Input:
C     pp    4 momentum of external particles
C     wgt   weight from Monte Carlo
C     imode 0 run, 1 init, 2 reweight, 
C     3 finalize, 4 only PDFs,
C     5 squared amplitude only (never
C     generate events)
C     Output:
C     Amplitude squared and summed
C     ****************************************************
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INCLUDE '../../Source/vector.inc'  ! defines VECSIZE_MEMMAX
      INCLUDE 'genps.inc'
      INCLUDE 'nexternal.inc'
      INCLUDE 'maxconfigs.inc'
      INCLUDE 'maxamps.inc'
      DOUBLE PRECISION       CONV
      PARAMETER (CONV=389379.66*1000)  !CONV TO PICOBARNS
      REAL*8     PI
      PARAMETER (PI=3.1415926D0)
C     
C     ARGUMENTS 
C     
      DOUBLE PRECISION ALL_PP(0:3,NEXTERNAL,VECSIZE_MEMMAX)
      DOUBLE PRECISION ALL_WGT(VECSIZE_MEMMAX)
      DOUBLE PRECISION ALL_XBK(2,VECSIZE_MEMMAX)
      DOUBLE PRECISION ALL_Q2FACT(2,VECSIZE_MEMMAX)
      DOUBLE PRECISION ALL_CM_RAP(VECSIZE_MEMMAX)
      INTEGER IMODE
      DOUBLE PRECISION ALL_OUT(VECSIZE_MEMMAX)
      INTEGER IMIRROR_VEC(*)
      INTEGER ICONF_VEC(*)
      INTEGER VECSIZE_USED
      INTEGER SYMCONF(0:LMAXCONFIGS)
      INTEGER CONFSUB(MAXSPROC,LMAXCONFIGS)
C     ----------
C     BEGIN CODE
C     ----------
C     
C     LOCAL VARIABLES 
C     
      INTEGER I,ITYPE,LP,IPROC
      DOUBLE PRECISION QSCALE
      DOUBLE PRECISION G1(VECSIZE_MEMMAX)
      DOUBLE PRECISION EM2(VECSIZE_MEMMAX)
      DOUBLE PRECISION XPQ(-7:7),PD(0:MAXPROC)
      DOUBLE PRECISION ALL_PD(0:MAXPROC, VECSIZE_MEMMAX)
      DOUBLE PRECISION DSIGUU,R,RCONF
      INTEGER LUN,ICONF,IFACT,NFACT
      DATA NFACT/1/
      SAVE NFACT
      DOUBLE PRECISION RHEL  ! random number
      INTEGER CHANNEL
C     
C     STUFF FOR DRESSED EE COLLISIONS
C     
      INCLUDE '../../Source/PDF/eepdf.inc'
      DOUBLE PRECISION EE_COMP_PROD

      INTEGER I_EE
C     
C     STUFF FOR UPC
C     
      DOUBLE PRECISION PHOTONPDFSQUARE
C     
C     EXTERNAL FUNCTIONS
C     
      LOGICAL PASSCUTS
      DOUBLE PRECISION ALPHAS2,REWGT,PDG2PDF,CUSTOM_BIAS
      INTEGER NEXTUNOPEN
      DOUBLE PRECISION DSIG2
C     
C     GLOBAL VARIABLES
C     
      INTEGER          IPSEL
      COMMON /SUBPROC/ IPSEL
C     MINCFIG has this config number
      INTEGER           MINCFIG, MAXCFIG
      COMMON/TO_CONFIGS/MINCFIG, MAXCFIG
      INTEGER MAPCONFIG(0:LMAXCONFIGS), ICONFIG
      COMMON/TO_MCONFIGS/MAPCONFIG, ICONFIG
C     Keep track of whether cuts already calculated for this event
      LOGICAL CUTSDONE,CUTSPASSED
      COMMON/TO_CUTSDONE/CUTSDONE,CUTSPASSED

      INTEGER SUBDIAG(MAXSPROC),IB(2)
      COMMON/TO_SUB_DIAG/SUBDIAG,IB
      INCLUDE 'run.inc'

      DOUBLE PRECISION P_MULTI(0:3, NEXTERNAL, VECSIZE_MEMMAX)
      DOUBLE PRECISION HEL_RAND(VECSIZE_MEMMAX)
      DOUBLE PRECISION COL_RAND(VECSIZE_MEMMAX)
      INTEGER SELECTED_HEL(VECSIZE_MEMMAX)
      INTEGER SELECTED_COL(VECSIZE_MEMMAX)
      DOUBLE PRECISION ALL_RWGT(VECSIZE_MEMMAX)

C     Common blocks
      INCLUDE '../../Source/PDF/pdf.inc'
C     CHARACTER*7         PDLABEL,EPA_LABEL
C     INTEGER       LHAID
C     COMMON/TO_PDF/LHAID,PDLABEL,EPA_LABEL     

C     
C     local
C     
      DOUBLE PRECISION P1(0:3, NEXTERNAL)
      INTEGER IVEC, CURR_WARP, IWARP, NB_WARP_USED
      INTEGER CHANNELS(VECSIZE_MEMMAX)
C     
C     DATA
C     
      DATA G1/VECSIZE_MEMMAX*1D0/
      DATA EM2/VECSIZE_MEMMAX*1D0/
C     ----------
C     BEGIN CODE
C     ----------
      SELECTED_HEL(:) = 0
      SELECTED_COL(:) = 0

      IF(IMODE.EQ.1)THEN
        NFACT = DSIG2(ALL_PP(0,1,1), ALL_WGT(1), IMODE)
        RETURN
      ENDIF

C     Continue only if IMODE is 0, 4 or 5
      IF(IMODE.NE.0.AND.IMODE.NE.4.AND.IMODE.NE.5) RETURN


      NB_WARP_USED = VECSIZE_USED / WARP_SIZE
      IF( NB_WARP_USED * WARP_SIZE .NE. VECSIZE_USED ) THEN
        WRITE(*,*) 'ERROR: NB_WARP_USED * WARP_SIZE .NE. VECSIZE_USED',
     &    NB_WARP_USED, WARP_SIZE, VECSIZE_USED
        STOP
      ENDIF

      DO CURR_WARP=1, NB_WARP_USED
        IF(IMIRROR_VEC(CURR_WARP).EQ.1)THEN
          IB(1) = 1
          IB(2) = 2
        ELSE
          IB(1) = 2
          IB(2) = 1
        ENDIF
        DO IWARP=1, WARP_SIZE
          IVEC = (CURR_WARP-1)*WARP_SIZE+IWARP
          IF (ABS(LPP(IB(1))).GE.1) THEN
C           LP=SIGN(1,LPP(IB(1)))
            G1(IVEC)=PDG2PDF(LPP(IB(1)),0, IB(1),ALL_XBK(IB(1),IVEC)
     $       ,DSQRT(ALL_Q2FACT(1, IVEC)))
          ENDIF
          IF (ABS(LPP(IB(2))).GE.1) THEN
C           LP=SIGN(1,LPP(IB(2)))
            EM2(IVEC)=PDG2PDF(LPP(IB(2)),11, IB(2),ALL_XBK(IB(2),IVEC)
     $       ,DSQRT(ALL_Q2FACT(2, IVEC)))
          ENDIF
        ENDDO  ! IWARP LOOP
      ENDDO  ! CURRWARP LOOP
      ALL_PD(0,:) = 0D0
      IPROC = 0
      IPROC=IPROC+1  ! g e- > e- b s~ c b~ mu- vm~
      DO IVEC=1, VECSIZE_USED
        ALL_PD(IPROC,IVEC)=G1(IVEC)*EM2(IVEC)
        ALL_PD(0,IVEC)=ALL_PD(0,IVEC)+DABS(ALL_PD(IPROC,IVEC))

      ENDDO


      IF (IMODE.EQ.4)THEN
        ALL_OUT(:) = ALL_PD(0,:)
        RETURN
      ENDIF

      DO CURR_WARP=1, NB_WARP_USED
        IF(IMIRROR_VEC(CURR_WARP).EQ.1)THEN
          IB(1) = 1
          IB(2) = 2
        ELSE
          IB(1) = 2
          IB(2) = 1
        ENDIF
        DO IWARP=1, WARP_SIZE
          IVEC = (CURR_WARP-1)*WARP_SIZE+IWARP
C         Do not need those three here. do I?	 
          XBK(:) = ALL_XBK(:,IVEC)
C         CM_RAP = ALL_CM_RAP(IVEC)
          Q2FACT(:) = ALL_Q2FACT(:, IVEC)


C         Select a flavor combination (need to do here for right sign)
          CALL RANMAR(R)
          IPSEL=0
          DO WHILE (R.GE.0D0 .AND. IPSEL.LT.IPROC)
            IPSEL=IPSEL+1
            R=R-DABS(ALL_PD(IPSEL,IVEC))/ALL_PD(0,IVEC)
          ENDDO

          CHANNELS(IVEC) = CONFSUB(2,SYMCONF(ICONF_VEC(CURR_WARP)))
          SUBDIAG(2) = CHANNELS(IVEC)  ! only valid if a single process
          CHANNEL = SUBDIAG(2)


          ALL_RWGT(IVEC) = REWGT(ALL_PP(0,1,IVEC), IVEC)

          IF(FRAME_ID.NE.6)THEN
            CALL BOOST_TO_FRAME(ALL_PP(0,1,IVEC), FRAME_ID, P_MULTI(0
     $       ,1,IVEC))
          ELSE
            P_MULTI(:,:,IVEC) = ALL_PP(:,:,IVEC)
          ENDIF
          CALL RANMAR(HEL_RAND(IVEC))
          CALL RANMAR(COL_RAND(IVEC))
        ENDDO  ! end loop on IWARP/IVEC	 
      ENDDO  ! end loop on the CURR_WARP
      CALL SMATRIX2_MULTI(P_MULTI, HEL_RAND, COL_RAND, CHANNELS,
     $  ALL_OUT , SELECTED_HEL, SELECTED_COL, VECSIZE_USED)


      DO CURR_WARP=1, NB_WARP_USED
        IF(IMIRROR_VEC(CURR_WARP).EQ.1)THEN
          IB(1) = 1
          IB(2) = 2
        ELSE
          IB(1) = 2
          IB(2) = 1
        ENDIF
        DO IWARP=1, WARP_SIZE
          IVEC = (CURR_WARP-1)*WARP_SIZE+IWARP
          DSIGUU = ALL_OUT(IVEC)
          IF (IMODE.EQ.5) THEN
            IF (DSIGUU.LT.1D199) THEN
              ALL_OUT(IVEC) = DSIGUU*CONV
            ELSE
              ALL_OUT(IVEC) = 0.0D0
            ENDIF
            RETURN
          ENDIF

          XBK(:) = ALL_XBK(:,IVEC)
C         CM_RAP = ALL_CM_RAP(IVEC)
          Q2FACT(:) = ALL_Q2FACT(:, IVEC)

          IF(FRAME_ID.NE.6)THEN
            CALL BOOST_TO_FRAME(ALL_PP(0,1,IVEC), FRAME_ID, P1)
          ELSE
            P1 = ALL_PP(:,:,IVEC)
          ENDIF
C         call restore_cl_val_to(ivec)
C         DSIGUU=DSIGUU*REWGT(P1,ivec)
          DSIGUU=DSIGUU*ALL_RWGT(IVEC)

C         Apply the bias weight specified in the run card (default is
C          1.0)
          DSIGUU=DSIGUU*CUSTOM_BIAS(P1,DSIGUU,2, IVEC)

          DSIGUU=DSIGUU*NFACT

          IF (DSIGUU.LT.1D199) THEN
C           Set sign of dsig based on sign of PDF and matrix element
            ALL_OUT(IVEC)=DSIGN(CONV*ALL_PD(0,IVEC)*DSIGUU,DSIGUU
     $       *ALL_PD(IPSEL,IVEC))
          ELSE
            WRITE(*,*) 'Error in matrix element'
            DSIGUU=0D0
            ALL_OUT(IVEC)=0D0
          ENDIF
C         Generate events only if IMODE is 0.
          IF(IMODE.EQ.0.AND.DABS(ALL_OUT(IVEC)).GT.0D0)THEN
C           Call UNWGT to unweight and store events
            ICONFIG = SYMCONF(ICONF_VEC(CURR_WARP))
            CALL UNWGT(ALL_PP(0,1,IVEC), ALL_OUT(IVEC)*ALL_WGT(IVEC),2
     $       , SELECTED_HEL(IVEC), SELECTED_COL(IVEC), IVEC)
          ENDIF
        ENDDO
      ENDDO

      END




      SUBROUTINE PRINT_ZERO_AMP2()

      RETURN
      END


      SUBROUTINE SMATRIX2_MULTI(P_MULTI, HEL_RAND, COL_RAND, CHANNELS,
     $  OUT, SELECTED_HEL, SELECTED_COL, VECSIZE_USED)
      USE OMP_LIB
      IMPLICIT NONE

      INCLUDE 'nexternal.inc'
      INCLUDE '../../Source/vector.inc'  ! defines VECSIZE_MEMMAX
      INCLUDE 'maxamps.inc'
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=512)
      DOUBLE PRECISION P_MULTI(0:3, NEXTERNAL, VECSIZE_MEMMAX)
      DOUBLE PRECISION HEL_RAND(VECSIZE_MEMMAX)
      DOUBLE PRECISION COL_RAND(VECSIZE_MEMMAX)
      INTEGER CHANNELS(VECSIZE_MEMMAX)
      DOUBLE PRECISION OUT(VECSIZE_MEMMAX)
      INTEGER SELECTED_HEL(VECSIZE_MEMMAX)
      INTEGER SELECTED_COL(VECSIZE_MEMMAX)
      INTEGER VECSIZE_USED

      INTEGER IVEC




!$OMP PARALLEL
!$OMP DO
      DO IVEC=1, VECSIZE_USED
        CALL SMATRIX2(P_MULTI(0,1,IVEC),
     &	                         hel_rand(IVEC),
     &                           col_rand(IVEC),
     &				 channels(IVEC),
     &                           IVEC,
     &				 out(IVEC),
     &				 selected_hel(IVEC),
     &				 selected_col(IVEC)
     &				 )
      ENDDO
!$OMP END DO
!$OMP END PARALLEL

      RETURN
      END

      INTEGER FUNCTION GET_NHEL2(HEL, IPART)
C     if hel>0 return the helicity of particule ipart for the selected
C      helicity configuration
C     if hel=0 return the number of helicity state possible for that
C      particle 
      IMPLICIT NONE
      INTEGER HEL,I, IPART
      INCLUDE 'nexternal.inc'
      INTEGER ONE_NHEL(NEXTERNAL)
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=512)
      INTEGER NHEL(NEXTERNAL,0:NCOMB)
      DATA (NHEL(I,0),I=1,5) / 2, 2, 2, 2, 2/
      DATA (NHEL(I,   1),I=1,9) /-1, 1,-1,-1, 1,-1, 1,-1, 1/
      DATA (NHEL(I,   2),I=1,9) /-1, 1,-1,-1, 1,-1, 1,-1,-1/
      DATA (NHEL(I,   3),I=1,9) /-1, 1,-1,-1, 1,-1, 1, 1, 1/
      DATA (NHEL(I,   4),I=1,9) /-1, 1,-1,-1, 1,-1, 1, 1,-1/
      DATA (NHEL(I,   5),I=1,9) /-1, 1,-1,-1, 1,-1,-1,-1, 1/
      DATA (NHEL(I,   6),I=1,9) /-1, 1,-1,-1, 1,-1,-1,-1,-1/
      DATA (NHEL(I,   7),I=1,9) /-1, 1,-1,-1, 1,-1,-1, 1, 1/
      DATA (NHEL(I,   8),I=1,9) /-1, 1,-1,-1, 1,-1,-1, 1,-1/
      DATA (NHEL(I,   9),I=1,9) /-1, 1,-1,-1, 1, 1, 1,-1, 1/
      DATA (NHEL(I,  10),I=1,9) /-1, 1,-1,-1, 1, 1, 1,-1,-1/
      DATA (NHEL(I,  11),I=1,9) /-1, 1,-1,-1, 1, 1, 1, 1, 1/
      DATA (NHEL(I,  12),I=1,9) /-1, 1,-1,-1, 1, 1, 1, 1,-1/
      DATA (NHEL(I,  13),I=1,9) /-1, 1,-1,-1, 1, 1,-1,-1, 1/
      DATA (NHEL(I,  14),I=1,9) /-1, 1,-1,-1, 1, 1,-1,-1,-1/
      DATA (NHEL(I,  15),I=1,9) /-1, 1,-1,-1, 1, 1,-1, 1, 1/
      DATA (NHEL(I,  16),I=1,9) /-1, 1,-1,-1, 1, 1,-1, 1,-1/
      DATA (NHEL(I,  17),I=1,9) /-1, 1,-1,-1,-1,-1, 1,-1, 1/
      DATA (NHEL(I,  18),I=1,9) /-1, 1,-1,-1,-1,-1, 1,-1,-1/
      DATA (NHEL(I,  19),I=1,9) /-1, 1,-1,-1,-1,-1, 1, 1, 1/
      DATA (NHEL(I,  20),I=1,9) /-1, 1,-1,-1,-1,-1, 1, 1,-1/
      DATA (NHEL(I,  21),I=1,9) /-1, 1,-1,-1,-1,-1,-1,-1, 1/
      DATA (NHEL(I,  22),I=1,9) /-1, 1,-1,-1,-1,-1,-1,-1,-1/
      DATA (NHEL(I,  23),I=1,9) /-1, 1,-1,-1,-1,-1,-1, 1, 1/
      DATA (NHEL(I,  24),I=1,9) /-1, 1,-1,-1,-1,-1,-1, 1,-1/
      DATA (NHEL(I,  25),I=1,9) /-1, 1,-1,-1,-1, 1, 1,-1, 1/
      DATA (NHEL(I,  26),I=1,9) /-1, 1,-1,-1,-1, 1, 1,-1,-1/
      DATA (NHEL(I,  27),I=1,9) /-1, 1,-1,-1,-1, 1, 1, 1, 1/
      DATA (NHEL(I,  28),I=1,9) /-1, 1,-1,-1,-1, 1, 1, 1,-1/
      DATA (NHEL(I,  29),I=1,9) /-1, 1,-1,-1,-1, 1,-1,-1, 1/
      DATA (NHEL(I,  30),I=1,9) /-1, 1,-1,-1,-1, 1,-1,-1,-1/
      DATA (NHEL(I,  31),I=1,9) /-1, 1,-1,-1,-1, 1,-1, 1, 1/
      DATA (NHEL(I,  32),I=1,9) /-1, 1,-1,-1,-1, 1,-1, 1,-1/
      DATA (NHEL(I,  33),I=1,9) /-1, 1,-1, 1, 1,-1, 1,-1, 1/
      DATA (NHEL(I,  34),I=1,9) /-1, 1,-1, 1, 1,-1, 1,-1,-1/
      DATA (NHEL(I,  35),I=1,9) /-1, 1,-1, 1, 1,-1, 1, 1, 1/
      DATA (NHEL(I,  36),I=1,9) /-1, 1,-1, 1, 1,-1, 1, 1,-1/
      DATA (NHEL(I,  37),I=1,9) /-1, 1,-1, 1, 1,-1,-1,-1, 1/
      DATA (NHEL(I,  38),I=1,9) /-1, 1,-1, 1, 1,-1,-1,-1,-1/
      DATA (NHEL(I,  39),I=1,9) /-1, 1,-1, 1, 1,-1,-1, 1, 1/
      DATA (NHEL(I,  40),I=1,9) /-1, 1,-1, 1, 1,-1,-1, 1,-1/
      DATA (NHEL(I,  41),I=1,9) /-1, 1,-1, 1, 1, 1, 1,-1, 1/
      DATA (NHEL(I,  42),I=1,9) /-1, 1,-1, 1, 1, 1, 1,-1,-1/
      DATA (NHEL(I,  43),I=1,9) /-1, 1,-1, 1, 1, 1, 1, 1, 1/
      DATA (NHEL(I,  44),I=1,9) /-1, 1,-1, 1, 1, 1, 1, 1,-1/
      DATA (NHEL(I,  45),I=1,9) /-1, 1,-1, 1, 1, 1,-1,-1, 1/
      DATA (NHEL(I,  46),I=1,9) /-1, 1,-1, 1, 1, 1,-1,-1,-1/
      DATA (NHEL(I,  47),I=1,9) /-1, 1,-1, 1, 1, 1,-1, 1, 1/
      DATA (NHEL(I,  48),I=1,9) /-1, 1,-1, 1, 1, 1,-1, 1,-1/
      DATA (NHEL(I,  49),I=1,9) /-1, 1,-1, 1,-1,-1, 1,-1, 1/
      DATA (NHEL(I,  50),I=1,9) /-1, 1,-1, 1,-1,-1, 1,-1,-1/
      DATA (NHEL(I,  51),I=1,9) /-1, 1,-1, 1,-1,-1, 1, 1, 1/
      DATA (NHEL(I,  52),I=1,9) /-1, 1,-1, 1,-1,-1, 1, 1,-1/
      DATA (NHEL(I,  53),I=1,9) /-1, 1,-1, 1,-1,-1,-1,-1, 1/
      DATA (NHEL(I,  54),I=1,9) /-1, 1,-1, 1,-1,-1,-1,-1,-1/
      DATA (NHEL(I,  55),I=1,9) /-1, 1,-1, 1,-1,-1,-1, 1, 1/
      DATA (NHEL(I,  56),I=1,9) /-1, 1,-1, 1,-1,-1,-1, 1,-1/
      DATA (NHEL(I,  57),I=1,9) /-1, 1,-1, 1,-1, 1, 1,-1, 1/
      DATA (NHEL(I,  58),I=1,9) /-1, 1,-1, 1,-1, 1, 1,-1,-1/
      DATA (NHEL(I,  59),I=1,9) /-1, 1,-1, 1,-1, 1, 1, 1, 1/
      DATA (NHEL(I,  60),I=1,9) /-1, 1,-1, 1,-1, 1, 1, 1,-1/
      DATA (NHEL(I,  61),I=1,9) /-1, 1,-1, 1,-1, 1,-1,-1, 1/
      DATA (NHEL(I,  62),I=1,9) /-1, 1,-1, 1,-1, 1,-1,-1,-1/
      DATA (NHEL(I,  63),I=1,9) /-1, 1,-1, 1,-1, 1,-1, 1, 1/
      DATA (NHEL(I,  64),I=1,9) /-1, 1,-1, 1,-1, 1,-1, 1,-1/
      DATA (NHEL(I,  65),I=1,9) /-1, 1, 1,-1, 1,-1, 1,-1, 1/
      DATA (NHEL(I,  66),I=1,9) /-1, 1, 1,-1, 1,-1, 1,-1,-1/
      DATA (NHEL(I,  67),I=1,9) /-1, 1, 1,-1, 1,-1, 1, 1, 1/
      DATA (NHEL(I,  68),I=1,9) /-1, 1, 1,-1, 1,-1, 1, 1,-1/
      DATA (NHEL(I,  69),I=1,9) /-1, 1, 1,-1, 1,-1,-1,-1, 1/
      DATA (NHEL(I,  70),I=1,9) /-1, 1, 1,-1, 1,-1,-1,-1,-1/
      DATA (NHEL(I,  71),I=1,9) /-1, 1, 1,-1, 1,-1,-1, 1, 1/
      DATA (NHEL(I,  72),I=1,9) /-1, 1, 1,-1, 1,-1,-1, 1,-1/
      DATA (NHEL(I,  73),I=1,9) /-1, 1, 1,-1, 1, 1, 1,-1, 1/
      DATA (NHEL(I,  74),I=1,9) /-1, 1, 1,-1, 1, 1, 1,-1,-1/
      DATA (NHEL(I,  75),I=1,9) /-1, 1, 1,-1, 1, 1, 1, 1, 1/
      DATA (NHEL(I,  76),I=1,9) /-1, 1, 1,-1, 1, 1, 1, 1,-1/
      DATA (NHEL(I,  77),I=1,9) /-1, 1, 1,-1, 1, 1,-1,-1, 1/
      DATA (NHEL(I,  78),I=1,9) /-1, 1, 1,-1, 1, 1,-1,-1,-1/
      DATA (NHEL(I,  79),I=1,9) /-1, 1, 1,-1, 1, 1,-1, 1, 1/
      DATA (NHEL(I,  80),I=1,9) /-1, 1, 1,-1, 1, 1,-1, 1,-1/
      DATA (NHEL(I,  81),I=1,9) /-1, 1, 1,-1,-1,-1, 1,-1, 1/
      DATA (NHEL(I,  82),I=1,9) /-1, 1, 1,-1,-1,-1, 1,-1,-1/
      DATA (NHEL(I,  83),I=1,9) /-1, 1, 1,-1,-1,-1, 1, 1, 1/
      DATA (NHEL(I,  84),I=1,9) /-1, 1, 1,-1,-1,-1, 1, 1,-1/
      DATA (NHEL(I,  85),I=1,9) /-1, 1, 1,-1,-1,-1,-1,-1, 1/
      DATA (NHEL(I,  86),I=1,9) /-1, 1, 1,-1,-1,-1,-1,-1,-1/
      DATA (NHEL(I,  87),I=1,9) /-1, 1, 1,-1,-1,-1,-1, 1, 1/
      DATA (NHEL(I,  88),I=1,9) /-1, 1, 1,-1,-1,-1,-1, 1,-1/
      DATA (NHEL(I,  89),I=1,9) /-1, 1, 1,-1,-1, 1, 1,-1, 1/
      DATA (NHEL(I,  90),I=1,9) /-1, 1, 1,-1,-1, 1, 1,-1,-1/
      DATA (NHEL(I,  91),I=1,9) /-1, 1, 1,-1,-1, 1, 1, 1, 1/
      DATA (NHEL(I,  92),I=1,9) /-1, 1, 1,-1,-1, 1, 1, 1,-1/
      DATA (NHEL(I,  93),I=1,9) /-1, 1, 1,-1,-1, 1,-1,-1, 1/
      DATA (NHEL(I,  94),I=1,9) /-1, 1, 1,-1,-1, 1,-1,-1,-1/
      DATA (NHEL(I,  95),I=1,9) /-1, 1, 1,-1,-1, 1,-1, 1, 1/
      DATA (NHEL(I,  96),I=1,9) /-1, 1, 1,-1,-1, 1,-1, 1,-1/
      DATA (NHEL(I,  97),I=1,9) /-1, 1, 1, 1, 1,-1, 1,-1, 1/
      DATA (NHEL(I,  98),I=1,9) /-1, 1, 1, 1, 1,-1, 1,-1,-1/
      DATA (NHEL(I,  99),I=1,9) /-1, 1, 1, 1, 1,-1, 1, 1, 1/
      DATA (NHEL(I, 100),I=1,9) /-1, 1, 1, 1, 1,-1, 1, 1,-1/
      DATA (NHEL(I, 101),I=1,9) /-1, 1, 1, 1, 1,-1,-1,-1, 1/
      DATA (NHEL(I, 102),I=1,9) /-1, 1, 1, 1, 1,-1,-1,-1,-1/
      DATA (NHEL(I, 103),I=1,9) /-1, 1, 1, 1, 1,-1,-1, 1, 1/
      DATA (NHEL(I, 104),I=1,9) /-1, 1, 1, 1, 1,-1,-1, 1,-1/
      DATA (NHEL(I, 105),I=1,9) /-1, 1, 1, 1, 1, 1, 1,-1, 1/
      DATA (NHEL(I, 106),I=1,9) /-1, 1, 1, 1, 1, 1, 1,-1,-1/
      DATA (NHEL(I, 107),I=1,9) /-1, 1, 1, 1, 1, 1, 1, 1, 1/
      DATA (NHEL(I, 108),I=1,9) /-1, 1, 1, 1, 1, 1, 1, 1,-1/
      DATA (NHEL(I, 109),I=1,9) /-1, 1, 1, 1, 1, 1,-1,-1, 1/
      DATA (NHEL(I, 110),I=1,9) /-1, 1, 1, 1, 1, 1,-1,-1,-1/
      DATA (NHEL(I, 111),I=1,9) /-1, 1, 1, 1, 1, 1,-1, 1, 1/
      DATA (NHEL(I, 112),I=1,9) /-1, 1, 1, 1, 1, 1,-1, 1,-1/
      DATA (NHEL(I, 113),I=1,9) /-1, 1, 1, 1,-1,-1, 1,-1, 1/
      DATA (NHEL(I, 114),I=1,9) /-1, 1, 1, 1,-1,-1, 1,-1,-1/
      DATA (NHEL(I, 115),I=1,9) /-1, 1, 1, 1,-1,-1, 1, 1, 1/
      DATA (NHEL(I, 116),I=1,9) /-1, 1, 1, 1,-1,-1, 1, 1,-1/
      DATA (NHEL(I, 117),I=1,9) /-1, 1, 1, 1,-1,-1,-1,-1, 1/
      DATA (NHEL(I, 118),I=1,9) /-1, 1, 1, 1,-1,-1,-1,-1,-1/
      DATA (NHEL(I, 119),I=1,9) /-1, 1, 1, 1,-1,-1,-1, 1, 1/
      DATA (NHEL(I, 120),I=1,9) /-1, 1, 1, 1,-1,-1,-1, 1,-1/
      DATA (NHEL(I, 121),I=1,9) /-1, 1, 1, 1,-1, 1, 1,-1, 1/
      DATA (NHEL(I, 122),I=1,9) /-1, 1, 1, 1,-1, 1, 1,-1,-1/
      DATA (NHEL(I, 123),I=1,9) /-1, 1, 1, 1,-1, 1, 1, 1, 1/
      DATA (NHEL(I, 124),I=1,9) /-1, 1, 1, 1,-1, 1, 1, 1,-1/
      DATA (NHEL(I, 125),I=1,9) /-1, 1, 1, 1,-1, 1,-1,-1, 1/
      DATA (NHEL(I, 126),I=1,9) /-1, 1, 1, 1,-1, 1,-1,-1,-1/
      DATA (NHEL(I, 127),I=1,9) /-1, 1, 1, 1,-1, 1,-1, 1, 1/
      DATA (NHEL(I, 128),I=1,9) /-1, 1, 1, 1,-1, 1,-1, 1,-1/
      DATA (NHEL(I, 129),I=1,9) /-1,-1,-1,-1, 1,-1, 1,-1, 1/
      DATA (NHEL(I, 130),I=1,9) /-1,-1,-1,-1, 1,-1, 1,-1,-1/
      DATA (NHEL(I, 131),I=1,9) /-1,-1,-1,-1, 1,-1, 1, 1, 1/
      DATA (NHEL(I, 132),I=1,9) /-1,-1,-1,-1, 1,-1, 1, 1,-1/
      DATA (NHEL(I, 133),I=1,9) /-1,-1,-1,-1, 1,-1,-1,-1, 1/
      DATA (NHEL(I, 134),I=1,9) /-1,-1,-1,-1, 1,-1,-1,-1,-1/
      DATA (NHEL(I, 135),I=1,9) /-1,-1,-1,-1, 1,-1,-1, 1, 1/
      DATA (NHEL(I, 136),I=1,9) /-1,-1,-1,-1, 1,-1,-1, 1,-1/
      DATA (NHEL(I, 137),I=1,9) /-1,-1,-1,-1, 1, 1, 1,-1, 1/
      DATA (NHEL(I, 138),I=1,9) /-1,-1,-1,-1, 1, 1, 1,-1,-1/
      DATA (NHEL(I, 139),I=1,9) /-1,-1,-1,-1, 1, 1, 1, 1, 1/
      DATA (NHEL(I, 140),I=1,9) /-1,-1,-1,-1, 1, 1, 1, 1,-1/
      DATA (NHEL(I, 141),I=1,9) /-1,-1,-1,-1, 1, 1,-1,-1, 1/
      DATA (NHEL(I, 142),I=1,9) /-1,-1,-1,-1, 1, 1,-1,-1,-1/
      DATA (NHEL(I, 143),I=1,9) /-1,-1,-1,-1, 1, 1,-1, 1, 1/
      DATA (NHEL(I, 144),I=1,9) /-1,-1,-1,-1, 1, 1,-1, 1,-1/
      DATA (NHEL(I, 145),I=1,9) /-1,-1,-1,-1,-1,-1, 1,-1, 1/
      DATA (NHEL(I, 146),I=1,9) /-1,-1,-1,-1,-1,-1, 1,-1,-1/
      DATA (NHEL(I, 147),I=1,9) /-1,-1,-1,-1,-1,-1, 1, 1, 1/
      DATA (NHEL(I, 148),I=1,9) /-1,-1,-1,-1,-1,-1, 1, 1,-1/
      DATA (NHEL(I, 149),I=1,9) /-1,-1,-1,-1,-1,-1,-1,-1, 1/
      DATA (NHEL(I, 150),I=1,9) /-1,-1,-1,-1,-1,-1,-1,-1,-1/
      DATA (NHEL(I, 151),I=1,9) /-1,-1,-1,-1,-1,-1,-1, 1, 1/
      DATA (NHEL(I, 152),I=1,9) /-1,-1,-1,-1,-1,-1,-1, 1,-1/
      DATA (NHEL(I, 153),I=1,9) /-1,-1,-1,-1,-1, 1, 1,-1, 1/
      DATA (NHEL(I, 154),I=1,9) /-1,-1,-1,-1,-1, 1, 1,-1,-1/
      DATA (NHEL(I, 155),I=1,9) /-1,-1,-1,-1,-1, 1, 1, 1, 1/
      DATA (NHEL(I, 156),I=1,9) /-1,-1,-1,-1,-1, 1, 1, 1,-1/
      DATA (NHEL(I, 157),I=1,9) /-1,-1,-1,-1,-1, 1,-1,-1, 1/
      DATA (NHEL(I, 158),I=1,9) /-1,-1,-1,-1,-1, 1,-1,-1,-1/
      DATA (NHEL(I, 159),I=1,9) /-1,-1,-1,-1,-1, 1,-1, 1, 1/
      DATA (NHEL(I, 160),I=1,9) /-1,-1,-1,-1,-1, 1,-1, 1,-1/
      DATA (NHEL(I, 161),I=1,9) /-1,-1,-1, 1, 1,-1, 1,-1, 1/
      DATA (NHEL(I, 162),I=1,9) /-1,-1,-1, 1, 1,-1, 1,-1,-1/
      DATA (NHEL(I, 163),I=1,9) /-1,-1,-1, 1, 1,-1, 1, 1, 1/
      DATA (NHEL(I, 164),I=1,9) /-1,-1,-1, 1, 1,-1, 1, 1,-1/
      DATA (NHEL(I, 165),I=1,9) /-1,-1,-1, 1, 1,-1,-1,-1, 1/
      DATA (NHEL(I, 166),I=1,9) /-1,-1,-1, 1, 1,-1,-1,-1,-1/
      DATA (NHEL(I, 167),I=1,9) /-1,-1,-1, 1, 1,-1,-1, 1, 1/
      DATA (NHEL(I, 168),I=1,9) /-1,-1,-1, 1, 1,-1,-1, 1,-1/
      DATA (NHEL(I, 169),I=1,9) /-1,-1,-1, 1, 1, 1, 1,-1, 1/
      DATA (NHEL(I, 170),I=1,9) /-1,-1,-1, 1, 1, 1, 1,-1,-1/
      DATA (NHEL(I, 171),I=1,9) /-1,-1,-1, 1, 1, 1, 1, 1, 1/
      DATA (NHEL(I, 172),I=1,9) /-1,-1,-1, 1, 1, 1, 1, 1,-1/
      DATA (NHEL(I, 173),I=1,9) /-1,-1,-1, 1, 1, 1,-1,-1, 1/
      DATA (NHEL(I, 174),I=1,9) /-1,-1,-1, 1, 1, 1,-1,-1,-1/
      DATA (NHEL(I, 175),I=1,9) /-1,-1,-1, 1, 1, 1,-1, 1, 1/
      DATA (NHEL(I, 176),I=1,9) /-1,-1,-1, 1, 1, 1,-1, 1,-1/
      DATA (NHEL(I, 177),I=1,9) /-1,-1,-1, 1,-1,-1, 1,-1, 1/
      DATA (NHEL(I, 178),I=1,9) /-1,-1,-1, 1,-1,-1, 1,-1,-1/
      DATA (NHEL(I, 179),I=1,9) /-1,-1,-1, 1,-1,-1, 1, 1, 1/
      DATA (NHEL(I, 180),I=1,9) /-1,-1,-1, 1,-1,-1, 1, 1,-1/
      DATA (NHEL(I, 181),I=1,9) /-1,-1,-1, 1,-1,-1,-1,-1, 1/
      DATA (NHEL(I, 182),I=1,9) /-1,-1,-1, 1,-1,-1,-1,-1,-1/
      DATA (NHEL(I, 183),I=1,9) /-1,-1,-1, 1,-1,-1,-1, 1, 1/
      DATA (NHEL(I, 184),I=1,9) /-1,-1,-1, 1,-1,-1,-1, 1,-1/
      DATA (NHEL(I, 185),I=1,9) /-1,-1,-1, 1,-1, 1, 1,-1, 1/
      DATA (NHEL(I, 186),I=1,9) /-1,-1,-1, 1,-1, 1, 1,-1,-1/
      DATA (NHEL(I, 187),I=1,9) /-1,-1,-1, 1,-1, 1, 1, 1, 1/
      DATA (NHEL(I, 188),I=1,9) /-1,-1,-1, 1,-1, 1, 1, 1,-1/
      DATA (NHEL(I, 189),I=1,9) /-1,-1,-1, 1,-1, 1,-1,-1, 1/
      DATA (NHEL(I, 190),I=1,9) /-1,-1,-1, 1,-1, 1,-1,-1,-1/
      DATA (NHEL(I, 191),I=1,9) /-1,-1,-1, 1,-1, 1,-1, 1, 1/
      DATA (NHEL(I, 192),I=1,9) /-1,-1,-1, 1,-1, 1,-1, 1,-1/
      DATA (NHEL(I, 193),I=1,9) /-1,-1, 1,-1, 1,-1, 1,-1, 1/
      DATA (NHEL(I, 194),I=1,9) /-1,-1, 1,-1, 1,-1, 1,-1,-1/
      DATA (NHEL(I, 195),I=1,9) /-1,-1, 1,-1, 1,-1, 1, 1, 1/
      DATA (NHEL(I, 196),I=1,9) /-1,-1, 1,-1, 1,-1, 1, 1,-1/
      DATA (NHEL(I, 197),I=1,9) /-1,-1, 1,-1, 1,-1,-1,-1, 1/
      DATA (NHEL(I, 198),I=1,9) /-1,-1, 1,-1, 1,-1,-1,-1,-1/
      DATA (NHEL(I, 199),I=1,9) /-1,-1, 1,-1, 1,-1,-1, 1, 1/
      DATA (NHEL(I, 200),I=1,9) /-1,-1, 1,-1, 1,-1,-1, 1,-1/
      DATA (NHEL(I, 201),I=1,9) /-1,-1, 1,-1, 1, 1, 1,-1, 1/
      DATA (NHEL(I, 202),I=1,9) /-1,-1, 1,-1, 1, 1, 1,-1,-1/
      DATA (NHEL(I, 203),I=1,9) /-1,-1, 1,-1, 1, 1, 1, 1, 1/
      DATA (NHEL(I, 204),I=1,9) /-1,-1, 1,-1, 1, 1, 1, 1,-1/
      DATA (NHEL(I, 205),I=1,9) /-1,-1, 1,-1, 1, 1,-1,-1, 1/
      DATA (NHEL(I, 206),I=1,9) /-1,-1, 1,-1, 1, 1,-1,-1,-1/
      DATA (NHEL(I, 207),I=1,9) /-1,-1, 1,-1, 1, 1,-1, 1, 1/
      DATA (NHEL(I, 208),I=1,9) /-1,-1, 1,-1, 1, 1,-1, 1,-1/
      DATA (NHEL(I, 209),I=1,9) /-1,-1, 1,-1,-1,-1, 1,-1, 1/
      DATA (NHEL(I, 210),I=1,9) /-1,-1, 1,-1,-1,-1, 1,-1,-1/
      DATA (NHEL(I, 211),I=1,9) /-1,-1, 1,-1,-1,-1, 1, 1, 1/
      DATA (NHEL(I, 212),I=1,9) /-1,-1, 1,-1,-1,-1, 1, 1,-1/
      DATA (NHEL(I, 213),I=1,9) /-1,-1, 1,-1,-1,-1,-1,-1, 1/
      DATA (NHEL(I, 214),I=1,9) /-1,-1, 1,-1,-1,-1,-1,-1,-1/
      DATA (NHEL(I, 215),I=1,9) /-1,-1, 1,-1,-1,-1,-1, 1, 1/
      DATA (NHEL(I, 216),I=1,9) /-1,-1, 1,-1,-1,-1,-1, 1,-1/
      DATA (NHEL(I, 217),I=1,9) /-1,-1, 1,-1,-1, 1, 1,-1, 1/
      DATA (NHEL(I, 218),I=1,9) /-1,-1, 1,-1,-1, 1, 1,-1,-1/
      DATA (NHEL(I, 219),I=1,9) /-1,-1, 1,-1,-1, 1, 1, 1, 1/
      DATA (NHEL(I, 220),I=1,9) /-1,-1, 1,-1,-1, 1, 1, 1,-1/
      DATA (NHEL(I, 221),I=1,9) /-1,-1, 1,-1,-1, 1,-1,-1, 1/
      DATA (NHEL(I, 222),I=1,9) /-1,-1, 1,-1,-1, 1,-1,-1,-1/
      DATA (NHEL(I, 223),I=1,9) /-1,-1, 1,-1,-1, 1,-1, 1, 1/
      DATA (NHEL(I, 224),I=1,9) /-1,-1, 1,-1,-1, 1,-1, 1,-1/
      DATA (NHEL(I, 225),I=1,9) /-1,-1, 1, 1, 1,-1, 1,-1, 1/
      DATA (NHEL(I, 226),I=1,9) /-1,-1, 1, 1, 1,-1, 1,-1,-1/
      DATA (NHEL(I, 227),I=1,9) /-1,-1, 1, 1, 1,-1, 1, 1, 1/
      DATA (NHEL(I, 228),I=1,9) /-1,-1, 1, 1, 1,-1, 1, 1,-1/
      DATA (NHEL(I, 229),I=1,9) /-1,-1, 1, 1, 1,-1,-1,-1, 1/
      DATA (NHEL(I, 230),I=1,9) /-1,-1, 1, 1, 1,-1,-1,-1,-1/
      DATA (NHEL(I, 231),I=1,9) /-1,-1, 1, 1, 1,-1,-1, 1, 1/
      DATA (NHEL(I, 232),I=1,9) /-1,-1, 1, 1, 1,-1,-1, 1,-1/
      DATA (NHEL(I, 233),I=1,9) /-1,-1, 1, 1, 1, 1, 1,-1, 1/
      DATA (NHEL(I, 234),I=1,9) /-1,-1, 1, 1, 1, 1, 1,-1,-1/
      DATA (NHEL(I, 235),I=1,9) /-1,-1, 1, 1, 1, 1, 1, 1, 1/
      DATA (NHEL(I, 236),I=1,9) /-1,-1, 1, 1, 1, 1, 1, 1,-1/
      DATA (NHEL(I, 237),I=1,9) /-1,-1, 1, 1, 1, 1,-1,-1, 1/
      DATA (NHEL(I, 238),I=1,9) /-1,-1, 1, 1, 1, 1,-1,-1,-1/
      DATA (NHEL(I, 239),I=1,9) /-1,-1, 1, 1, 1, 1,-1, 1, 1/
      DATA (NHEL(I, 240),I=1,9) /-1,-1, 1, 1, 1, 1,-1, 1,-1/
      DATA (NHEL(I, 241),I=1,9) /-1,-1, 1, 1,-1,-1, 1,-1, 1/
      DATA (NHEL(I, 242),I=1,9) /-1,-1, 1, 1,-1,-1, 1,-1,-1/
      DATA (NHEL(I, 243),I=1,9) /-1,-1, 1, 1,-1,-1, 1, 1, 1/
      DATA (NHEL(I, 244),I=1,9) /-1,-1, 1, 1,-1,-1, 1, 1,-1/
      DATA (NHEL(I, 245),I=1,9) /-1,-1, 1, 1,-1,-1,-1,-1, 1/
      DATA (NHEL(I, 246),I=1,9) /-1,-1, 1, 1,-1,-1,-1,-1,-1/
      DATA (NHEL(I, 247),I=1,9) /-1,-1, 1, 1,-1,-1,-1, 1, 1/
      DATA (NHEL(I, 248),I=1,9) /-1,-1, 1, 1,-1,-1,-1, 1,-1/
      DATA (NHEL(I, 249),I=1,9) /-1,-1, 1, 1,-1, 1, 1,-1, 1/
      DATA (NHEL(I, 250),I=1,9) /-1,-1, 1, 1,-1, 1, 1,-1,-1/
      DATA (NHEL(I, 251),I=1,9) /-1,-1, 1, 1,-1, 1, 1, 1, 1/
      DATA (NHEL(I, 252),I=1,9) /-1,-1, 1, 1,-1, 1, 1, 1,-1/
      DATA (NHEL(I, 253),I=1,9) /-1,-1, 1, 1,-1, 1,-1,-1, 1/
      DATA (NHEL(I, 254),I=1,9) /-1,-1, 1, 1,-1, 1,-1,-1,-1/
      DATA (NHEL(I, 255),I=1,9) /-1,-1, 1, 1,-1, 1,-1, 1, 1/
      DATA (NHEL(I, 256),I=1,9) /-1,-1, 1, 1,-1, 1,-1, 1,-1/
      DATA (NHEL(I, 257),I=1,9) / 1, 1,-1,-1, 1,-1, 1,-1, 1/
      DATA (NHEL(I, 258),I=1,9) / 1, 1,-1,-1, 1,-1, 1,-1,-1/
      DATA (NHEL(I, 259),I=1,9) / 1, 1,-1,-1, 1,-1, 1, 1, 1/
      DATA (NHEL(I, 260),I=1,9) / 1, 1,-1,-1, 1,-1, 1, 1,-1/
      DATA (NHEL(I, 261),I=1,9) / 1, 1,-1,-1, 1,-1,-1,-1, 1/
      DATA (NHEL(I, 262),I=1,9) / 1, 1,-1,-1, 1,-1,-1,-1,-1/
      DATA (NHEL(I, 263),I=1,9) / 1, 1,-1,-1, 1,-1,-1, 1, 1/
      DATA (NHEL(I, 264),I=1,9) / 1, 1,-1,-1, 1,-1,-1, 1,-1/
      DATA (NHEL(I, 265),I=1,9) / 1, 1,-1,-1, 1, 1, 1,-1, 1/
      DATA (NHEL(I, 266),I=1,9) / 1, 1,-1,-1, 1, 1, 1,-1,-1/
      DATA (NHEL(I, 267),I=1,9) / 1, 1,-1,-1, 1, 1, 1, 1, 1/
      DATA (NHEL(I, 268),I=1,9) / 1, 1,-1,-1, 1, 1, 1, 1,-1/
      DATA (NHEL(I, 269),I=1,9) / 1, 1,-1,-1, 1, 1,-1,-1, 1/
      DATA (NHEL(I, 270),I=1,9) / 1, 1,-1,-1, 1, 1,-1,-1,-1/
      DATA (NHEL(I, 271),I=1,9) / 1, 1,-1,-1, 1, 1,-1, 1, 1/
      DATA (NHEL(I, 272),I=1,9) / 1, 1,-1,-1, 1, 1,-1, 1,-1/
      DATA (NHEL(I, 273),I=1,9) / 1, 1,-1,-1,-1,-1, 1,-1, 1/
      DATA (NHEL(I, 274),I=1,9) / 1, 1,-1,-1,-1,-1, 1,-1,-1/
      DATA (NHEL(I, 275),I=1,9) / 1, 1,-1,-1,-1,-1, 1, 1, 1/
      DATA (NHEL(I, 276),I=1,9) / 1, 1,-1,-1,-1,-1, 1, 1,-1/
      DATA (NHEL(I, 277),I=1,9) / 1, 1,-1,-1,-1,-1,-1,-1, 1/
      DATA (NHEL(I, 278),I=1,9) / 1, 1,-1,-1,-1,-1,-1,-1,-1/
      DATA (NHEL(I, 279),I=1,9) / 1, 1,-1,-1,-1,-1,-1, 1, 1/
      DATA (NHEL(I, 280),I=1,9) / 1, 1,-1,-1,-1,-1,-1, 1,-1/
      DATA (NHEL(I, 281),I=1,9) / 1, 1,-1,-1,-1, 1, 1,-1, 1/
      DATA (NHEL(I, 282),I=1,9) / 1, 1,-1,-1,-1, 1, 1,-1,-1/
      DATA (NHEL(I, 283),I=1,9) / 1, 1,-1,-1,-1, 1, 1, 1, 1/
      DATA (NHEL(I, 284),I=1,9) / 1, 1,-1,-1,-1, 1, 1, 1,-1/
      DATA (NHEL(I, 285),I=1,9) / 1, 1,-1,-1,-1, 1,-1,-1, 1/
      DATA (NHEL(I, 286),I=1,9) / 1, 1,-1,-1,-1, 1,-1,-1,-1/
      DATA (NHEL(I, 287),I=1,9) / 1, 1,-1,-1,-1, 1,-1, 1, 1/
      DATA (NHEL(I, 288),I=1,9) / 1, 1,-1,-1,-1, 1,-1, 1,-1/
      DATA (NHEL(I, 289),I=1,9) / 1, 1,-1, 1, 1,-1, 1,-1, 1/
      DATA (NHEL(I, 290),I=1,9) / 1, 1,-1, 1, 1,-1, 1,-1,-1/
      DATA (NHEL(I, 291),I=1,9) / 1, 1,-1, 1, 1,-1, 1, 1, 1/
      DATA (NHEL(I, 292),I=1,9) / 1, 1,-1, 1, 1,-1, 1, 1,-1/
      DATA (NHEL(I, 293),I=1,9) / 1, 1,-1, 1, 1,-1,-1,-1, 1/
      DATA (NHEL(I, 294),I=1,9) / 1, 1,-1, 1, 1,-1,-1,-1,-1/
      DATA (NHEL(I, 295),I=1,9) / 1, 1,-1, 1, 1,-1,-1, 1, 1/
      DATA (NHEL(I, 296),I=1,9) / 1, 1,-1, 1, 1,-1,-1, 1,-1/
      DATA (NHEL(I, 297),I=1,9) / 1, 1,-1, 1, 1, 1, 1,-1, 1/
      DATA (NHEL(I, 298),I=1,9) / 1, 1,-1, 1, 1, 1, 1,-1,-1/
      DATA (NHEL(I, 299),I=1,9) / 1, 1,-1, 1, 1, 1, 1, 1, 1/
      DATA (NHEL(I, 300),I=1,9) / 1, 1,-1, 1, 1, 1, 1, 1,-1/
      DATA (NHEL(I, 301),I=1,9) / 1, 1,-1, 1, 1, 1,-1,-1, 1/
      DATA (NHEL(I, 302),I=1,9) / 1, 1,-1, 1, 1, 1,-1,-1,-1/
      DATA (NHEL(I, 303),I=1,9) / 1, 1,-1, 1, 1, 1,-1, 1, 1/
      DATA (NHEL(I, 304),I=1,9) / 1, 1,-1, 1, 1, 1,-1, 1,-1/
      DATA (NHEL(I, 305),I=1,9) / 1, 1,-1, 1,-1,-1, 1,-1, 1/
      DATA (NHEL(I, 306),I=1,9) / 1, 1,-1, 1,-1,-1, 1,-1,-1/
      DATA (NHEL(I, 307),I=1,9) / 1, 1,-1, 1,-1,-1, 1, 1, 1/
      DATA (NHEL(I, 308),I=1,9) / 1, 1,-1, 1,-1,-1, 1, 1,-1/
      DATA (NHEL(I, 309),I=1,9) / 1, 1,-1, 1,-1,-1,-1,-1, 1/
      DATA (NHEL(I, 310),I=1,9) / 1, 1,-1, 1,-1,-1,-1,-1,-1/
      DATA (NHEL(I, 311),I=1,9) / 1, 1,-1, 1,-1,-1,-1, 1, 1/
      DATA (NHEL(I, 312),I=1,9) / 1, 1,-1, 1,-1,-1,-1, 1,-1/
      DATA (NHEL(I, 313),I=1,9) / 1, 1,-1, 1,-1, 1, 1,-1, 1/
      DATA (NHEL(I, 314),I=1,9) / 1, 1,-1, 1,-1, 1, 1,-1,-1/
      DATA (NHEL(I, 315),I=1,9) / 1, 1,-1, 1,-1, 1, 1, 1, 1/
      DATA (NHEL(I, 316),I=1,9) / 1, 1,-1, 1,-1, 1, 1, 1,-1/
      DATA (NHEL(I, 317),I=1,9) / 1, 1,-1, 1,-1, 1,-1,-1, 1/
      DATA (NHEL(I, 318),I=1,9) / 1, 1,-1, 1,-1, 1,-1,-1,-1/
      DATA (NHEL(I, 319),I=1,9) / 1, 1,-1, 1,-1, 1,-1, 1, 1/
      DATA (NHEL(I, 320),I=1,9) / 1, 1,-1, 1,-1, 1,-1, 1,-1/
      DATA (NHEL(I, 321),I=1,9) / 1, 1, 1,-1, 1,-1, 1,-1, 1/
      DATA (NHEL(I, 322),I=1,9) / 1, 1, 1,-1, 1,-1, 1,-1,-1/
      DATA (NHEL(I, 323),I=1,9) / 1, 1, 1,-1, 1,-1, 1, 1, 1/
      DATA (NHEL(I, 324),I=1,9) / 1, 1, 1,-1, 1,-1, 1, 1,-1/
      DATA (NHEL(I, 325),I=1,9) / 1, 1, 1,-1, 1,-1,-1,-1, 1/
      DATA (NHEL(I, 326),I=1,9) / 1, 1, 1,-1, 1,-1,-1,-1,-1/
      DATA (NHEL(I, 327),I=1,9) / 1, 1, 1,-1, 1,-1,-1, 1, 1/
      DATA (NHEL(I, 328),I=1,9) / 1, 1, 1,-1, 1,-1,-1, 1,-1/
      DATA (NHEL(I, 329),I=1,9) / 1, 1, 1,-1, 1, 1, 1,-1, 1/
      DATA (NHEL(I, 330),I=1,9) / 1, 1, 1,-1, 1, 1, 1,-1,-1/
      DATA (NHEL(I, 331),I=1,9) / 1, 1, 1,-1, 1, 1, 1, 1, 1/
      DATA (NHEL(I, 332),I=1,9) / 1, 1, 1,-1, 1, 1, 1, 1,-1/
      DATA (NHEL(I, 333),I=1,9) / 1, 1, 1,-1, 1, 1,-1,-1, 1/
      DATA (NHEL(I, 334),I=1,9) / 1, 1, 1,-1, 1, 1,-1,-1,-1/
      DATA (NHEL(I, 335),I=1,9) / 1, 1, 1,-1, 1, 1,-1, 1, 1/
      DATA (NHEL(I, 336),I=1,9) / 1, 1, 1,-1, 1, 1,-1, 1,-1/
      DATA (NHEL(I, 337),I=1,9) / 1, 1, 1,-1,-1,-1, 1,-1, 1/
      DATA (NHEL(I, 338),I=1,9) / 1, 1, 1,-1,-1,-1, 1,-1,-1/
      DATA (NHEL(I, 339),I=1,9) / 1, 1, 1,-1,-1,-1, 1, 1, 1/
      DATA (NHEL(I, 340),I=1,9) / 1, 1, 1,-1,-1,-1, 1, 1,-1/
      DATA (NHEL(I, 341),I=1,9) / 1, 1, 1,-1,-1,-1,-1,-1, 1/
      DATA (NHEL(I, 342),I=1,9) / 1, 1, 1,-1,-1,-1,-1,-1,-1/
      DATA (NHEL(I, 343),I=1,9) / 1, 1, 1,-1,-1,-1,-1, 1, 1/
      DATA (NHEL(I, 344),I=1,9) / 1, 1, 1,-1,-1,-1,-1, 1,-1/
      DATA (NHEL(I, 345),I=1,9) / 1, 1, 1,-1,-1, 1, 1,-1, 1/
      DATA (NHEL(I, 346),I=1,9) / 1, 1, 1,-1,-1, 1, 1,-1,-1/
      DATA (NHEL(I, 347),I=1,9) / 1, 1, 1,-1,-1, 1, 1, 1, 1/
      DATA (NHEL(I, 348),I=1,9) / 1, 1, 1,-1,-1, 1, 1, 1,-1/
      DATA (NHEL(I, 349),I=1,9) / 1, 1, 1,-1,-1, 1,-1,-1, 1/
      DATA (NHEL(I, 350),I=1,9) / 1, 1, 1,-1,-1, 1,-1,-1,-1/
      DATA (NHEL(I, 351),I=1,9) / 1, 1, 1,-1,-1, 1,-1, 1, 1/
      DATA (NHEL(I, 352),I=1,9) / 1, 1, 1,-1,-1, 1,-1, 1,-1/
      DATA (NHEL(I, 353),I=1,9) / 1, 1, 1, 1, 1,-1, 1,-1, 1/
      DATA (NHEL(I, 354),I=1,9) / 1, 1, 1, 1, 1,-1, 1,-1,-1/
      DATA (NHEL(I, 355),I=1,9) / 1, 1, 1, 1, 1,-1, 1, 1, 1/
      DATA (NHEL(I, 356),I=1,9) / 1, 1, 1, 1, 1,-1, 1, 1,-1/
      DATA (NHEL(I, 357),I=1,9) / 1, 1, 1, 1, 1,-1,-1,-1, 1/
      DATA (NHEL(I, 358),I=1,9) / 1, 1, 1, 1, 1,-1,-1,-1,-1/
      DATA (NHEL(I, 359),I=1,9) / 1, 1, 1, 1, 1,-1,-1, 1, 1/
      DATA (NHEL(I, 360),I=1,9) / 1, 1, 1, 1, 1,-1,-1, 1,-1/
      DATA (NHEL(I, 361),I=1,9) / 1, 1, 1, 1, 1, 1, 1,-1, 1/
      DATA (NHEL(I, 362),I=1,9) / 1, 1, 1, 1, 1, 1, 1,-1,-1/
      DATA (NHEL(I, 363),I=1,9) / 1, 1, 1, 1, 1, 1, 1, 1, 1/
      DATA (NHEL(I, 364),I=1,9) / 1, 1, 1, 1, 1, 1, 1, 1,-1/
      DATA (NHEL(I, 365),I=1,9) / 1, 1, 1, 1, 1, 1,-1,-1, 1/
      DATA (NHEL(I, 366),I=1,9) / 1, 1, 1, 1, 1, 1,-1,-1,-1/
      DATA (NHEL(I, 367),I=1,9) / 1, 1, 1, 1, 1, 1,-1, 1, 1/
      DATA (NHEL(I, 368),I=1,9) / 1, 1, 1, 1, 1, 1,-1, 1,-1/
      DATA (NHEL(I, 369),I=1,9) / 1, 1, 1, 1,-1,-1, 1,-1, 1/
      DATA (NHEL(I, 370),I=1,9) / 1, 1, 1, 1,-1,-1, 1,-1,-1/
      DATA (NHEL(I, 371),I=1,9) / 1, 1, 1, 1,-1,-1, 1, 1, 1/
      DATA (NHEL(I, 372),I=1,9) / 1, 1, 1, 1,-1,-1, 1, 1,-1/
      DATA (NHEL(I, 373),I=1,9) / 1, 1, 1, 1,-1,-1,-1,-1, 1/
      DATA (NHEL(I, 374),I=1,9) / 1, 1, 1, 1,-1,-1,-1,-1,-1/
      DATA (NHEL(I, 375),I=1,9) / 1, 1, 1, 1,-1,-1,-1, 1, 1/
      DATA (NHEL(I, 376),I=1,9) / 1, 1, 1, 1,-1,-1,-1, 1,-1/
      DATA (NHEL(I, 377),I=1,9) / 1, 1, 1, 1,-1, 1, 1,-1, 1/
      DATA (NHEL(I, 378),I=1,9) / 1, 1, 1, 1,-1, 1, 1,-1,-1/
      DATA (NHEL(I, 379),I=1,9) / 1, 1, 1, 1,-1, 1, 1, 1, 1/
      DATA (NHEL(I, 380),I=1,9) / 1, 1, 1, 1,-1, 1, 1, 1,-1/
      DATA (NHEL(I, 381),I=1,9) / 1, 1, 1, 1,-1, 1,-1,-1, 1/
      DATA (NHEL(I, 382),I=1,9) / 1, 1, 1, 1,-1, 1,-1,-1,-1/
      DATA (NHEL(I, 383),I=1,9) / 1, 1, 1, 1,-1, 1,-1, 1, 1/
      DATA (NHEL(I, 384),I=1,9) / 1, 1, 1, 1,-1, 1,-1, 1,-1/
      DATA (NHEL(I, 385),I=1,9) / 1,-1,-1,-1, 1,-1, 1,-1, 1/
      DATA (NHEL(I, 386),I=1,9) / 1,-1,-1,-1, 1,-1, 1,-1,-1/
      DATA (NHEL(I, 387),I=1,9) / 1,-1,-1,-1, 1,-1, 1, 1, 1/
      DATA (NHEL(I, 388),I=1,9) / 1,-1,-1,-1, 1,-1, 1, 1,-1/
      DATA (NHEL(I, 389),I=1,9) / 1,-1,-1,-1, 1,-1,-1,-1, 1/
      DATA (NHEL(I, 390),I=1,9) / 1,-1,-1,-1, 1,-1,-1,-1,-1/
      DATA (NHEL(I, 391),I=1,9) / 1,-1,-1,-1, 1,-1,-1, 1, 1/
      DATA (NHEL(I, 392),I=1,9) / 1,-1,-1,-1, 1,-1,-1, 1,-1/
      DATA (NHEL(I, 393),I=1,9) / 1,-1,-1,-1, 1, 1, 1,-1, 1/
      DATA (NHEL(I, 394),I=1,9) / 1,-1,-1,-1, 1, 1, 1,-1,-1/
      DATA (NHEL(I, 395),I=1,9) / 1,-1,-1,-1, 1, 1, 1, 1, 1/
      DATA (NHEL(I, 396),I=1,9) / 1,-1,-1,-1, 1, 1, 1, 1,-1/
      DATA (NHEL(I, 397),I=1,9) / 1,-1,-1,-1, 1, 1,-1,-1, 1/
      DATA (NHEL(I, 398),I=1,9) / 1,-1,-1,-1, 1, 1,-1,-1,-1/
      DATA (NHEL(I, 399),I=1,9) / 1,-1,-1,-1, 1, 1,-1, 1, 1/
      DATA (NHEL(I, 400),I=1,9) / 1,-1,-1,-1, 1, 1,-1, 1,-1/
      DATA (NHEL(I, 401),I=1,9) / 1,-1,-1,-1,-1,-1, 1,-1, 1/
      DATA (NHEL(I, 402),I=1,9) / 1,-1,-1,-1,-1,-1, 1,-1,-1/
      DATA (NHEL(I, 403),I=1,9) / 1,-1,-1,-1,-1,-1, 1, 1, 1/
      DATA (NHEL(I, 404),I=1,9) / 1,-1,-1,-1,-1,-1, 1, 1,-1/
      DATA (NHEL(I, 405),I=1,9) / 1,-1,-1,-1,-1,-1,-1,-1, 1/
      DATA (NHEL(I, 406),I=1,9) / 1,-1,-1,-1,-1,-1,-1,-1,-1/
      DATA (NHEL(I, 407),I=1,9) / 1,-1,-1,-1,-1,-1,-1, 1, 1/
      DATA (NHEL(I, 408),I=1,9) / 1,-1,-1,-1,-1,-1,-1, 1,-1/
      DATA (NHEL(I, 409),I=1,9) / 1,-1,-1,-1,-1, 1, 1,-1, 1/
      DATA (NHEL(I, 410),I=1,9) / 1,-1,-1,-1,-1, 1, 1,-1,-1/
      DATA (NHEL(I, 411),I=1,9) / 1,-1,-1,-1,-1, 1, 1, 1, 1/
      DATA (NHEL(I, 412),I=1,9) / 1,-1,-1,-1,-1, 1, 1, 1,-1/
      DATA (NHEL(I, 413),I=1,9) / 1,-1,-1,-1,-1, 1,-1,-1, 1/
      DATA (NHEL(I, 414),I=1,9) / 1,-1,-1,-1,-1, 1,-1,-1,-1/
      DATA (NHEL(I, 415),I=1,9) / 1,-1,-1,-1,-1, 1,-1, 1, 1/
      DATA (NHEL(I, 416),I=1,9) / 1,-1,-1,-1,-1, 1,-1, 1,-1/
      DATA (NHEL(I, 417),I=1,9) / 1,-1,-1, 1, 1,-1, 1,-1, 1/
      DATA (NHEL(I, 418),I=1,9) / 1,-1,-1, 1, 1,-1, 1,-1,-1/
      DATA (NHEL(I, 419),I=1,9) / 1,-1,-1, 1, 1,-1, 1, 1, 1/
      DATA (NHEL(I, 420),I=1,9) / 1,-1,-1, 1, 1,-1, 1, 1,-1/
      DATA (NHEL(I, 421),I=1,9) / 1,-1,-1, 1, 1,-1,-1,-1, 1/
      DATA (NHEL(I, 422),I=1,9) / 1,-1,-1, 1, 1,-1,-1,-1,-1/
      DATA (NHEL(I, 423),I=1,9) / 1,-1,-1, 1, 1,-1,-1, 1, 1/
      DATA (NHEL(I, 424),I=1,9) / 1,-1,-1, 1, 1,-1,-1, 1,-1/
      DATA (NHEL(I, 425),I=1,9) / 1,-1,-1, 1, 1, 1, 1,-1, 1/
      DATA (NHEL(I, 426),I=1,9) / 1,-1,-1, 1, 1, 1, 1,-1,-1/
      DATA (NHEL(I, 427),I=1,9) / 1,-1,-1, 1, 1, 1, 1, 1, 1/
      DATA (NHEL(I, 428),I=1,9) / 1,-1,-1, 1, 1, 1, 1, 1,-1/
      DATA (NHEL(I, 429),I=1,9) / 1,-1,-1, 1, 1, 1,-1,-1, 1/
      DATA (NHEL(I, 430),I=1,9) / 1,-1,-1, 1, 1, 1,-1,-1,-1/
      DATA (NHEL(I, 431),I=1,9) / 1,-1,-1, 1, 1, 1,-1, 1, 1/
      DATA (NHEL(I, 432),I=1,9) / 1,-1,-1, 1, 1, 1,-1, 1,-1/
      DATA (NHEL(I, 433),I=1,9) / 1,-1,-1, 1,-1,-1, 1,-1, 1/
      DATA (NHEL(I, 434),I=1,9) / 1,-1,-1, 1,-1,-1, 1,-1,-1/
      DATA (NHEL(I, 435),I=1,9) / 1,-1,-1, 1,-1,-1, 1, 1, 1/
      DATA (NHEL(I, 436),I=1,9) / 1,-1,-1, 1,-1,-1, 1, 1,-1/
      DATA (NHEL(I, 437),I=1,9) / 1,-1,-1, 1,-1,-1,-1,-1, 1/
      DATA (NHEL(I, 438),I=1,9) / 1,-1,-1, 1,-1,-1,-1,-1,-1/
      DATA (NHEL(I, 439),I=1,9) / 1,-1,-1, 1,-1,-1,-1, 1, 1/
      DATA (NHEL(I, 440),I=1,9) / 1,-1,-1, 1,-1,-1,-1, 1,-1/
      DATA (NHEL(I, 441),I=1,9) / 1,-1,-1, 1,-1, 1, 1,-1, 1/
      DATA (NHEL(I, 442),I=1,9) / 1,-1,-1, 1,-1, 1, 1,-1,-1/
      DATA (NHEL(I, 443),I=1,9) / 1,-1,-1, 1,-1, 1, 1, 1, 1/
      DATA (NHEL(I, 444),I=1,9) / 1,-1,-1, 1,-1, 1, 1, 1,-1/
      DATA (NHEL(I, 445),I=1,9) / 1,-1,-1, 1,-1, 1,-1,-1, 1/
      DATA (NHEL(I, 446),I=1,9) / 1,-1,-1, 1,-1, 1,-1,-1,-1/
      DATA (NHEL(I, 447),I=1,9) / 1,-1,-1, 1,-1, 1,-1, 1, 1/
      DATA (NHEL(I, 448),I=1,9) / 1,-1,-1, 1,-1, 1,-1, 1,-1/
      DATA (NHEL(I, 449),I=1,9) / 1,-1, 1,-1, 1,-1, 1,-1, 1/
      DATA (NHEL(I, 450),I=1,9) / 1,-1, 1,-1, 1,-1, 1,-1,-1/
      DATA (NHEL(I, 451),I=1,9) / 1,-1, 1,-1, 1,-1, 1, 1, 1/
      DATA (NHEL(I, 452),I=1,9) / 1,-1, 1,-1, 1,-1, 1, 1,-1/
      DATA (NHEL(I, 453),I=1,9) / 1,-1, 1,-1, 1,-1,-1,-1, 1/
      DATA (NHEL(I, 454),I=1,9) / 1,-1, 1,-1, 1,-1,-1,-1,-1/
      DATA (NHEL(I, 455),I=1,9) / 1,-1, 1,-1, 1,-1,-1, 1, 1/
      DATA (NHEL(I, 456),I=1,9) / 1,-1, 1,-1, 1,-1,-1, 1,-1/
      DATA (NHEL(I, 457),I=1,9) / 1,-1, 1,-1, 1, 1, 1,-1, 1/
      DATA (NHEL(I, 458),I=1,9) / 1,-1, 1,-1, 1, 1, 1,-1,-1/
      DATA (NHEL(I, 459),I=1,9) / 1,-1, 1,-1, 1, 1, 1, 1, 1/
      DATA (NHEL(I, 460),I=1,9) / 1,-1, 1,-1, 1, 1, 1, 1,-1/
      DATA (NHEL(I, 461),I=1,9) / 1,-1, 1,-1, 1, 1,-1,-1, 1/
      DATA (NHEL(I, 462),I=1,9) / 1,-1, 1,-1, 1, 1,-1,-1,-1/
      DATA (NHEL(I, 463),I=1,9) / 1,-1, 1,-1, 1, 1,-1, 1, 1/
      DATA (NHEL(I, 464),I=1,9) / 1,-1, 1,-1, 1, 1,-1, 1,-1/
      DATA (NHEL(I, 465),I=1,9) / 1,-1, 1,-1,-1,-1, 1,-1, 1/
      DATA (NHEL(I, 466),I=1,9) / 1,-1, 1,-1,-1,-1, 1,-1,-1/
      DATA (NHEL(I, 467),I=1,9) / 1,-1, 1,-1,-1,-1, 1, 1, 1/
      DATA (NHEL(I, 468),I=1,9) / 1,-1, 1,-1,-1,-1, 1, 1,-1/
      DATA (NHEL(I, 469),I=1,9) / 1,-1, 1,-1,-1,-1,-1,-1, 1/
      DATA (NHEL(I, 470),I=1,9) / 1,-1, 1,-1,-1,-1,-1,-1,-1/
      DATA (NHEL(I, 471),I=1,9) / 1,-1, 1,-1,-1,-1,-1, 1, 1/
      DATA (NHEL(I, 472),I=1,9) / 1,-1, 1,-1,-1,-1,-1, 1,-1/
      DATA (NHEL(I, 473),I=1,9) / 1,-1, 1,-1,-1, 1, 1,-1, 1/
      DATA (NHEL(I, 474),I=1,9) / 1,-1, 1,-1,-1, 1, 1,-1,-1/
      DATA (NHEL(I, 475),I=1,9) / 1,-1, 1,-1,-1, 1, 1, 1, 1/
      DATA (NHEL(I, 476),I=1,9) / 1,-1, 1,-1,-1, 1, 1, 1,-1/
      DATA (NHEL(I, 477),I=1,9) / 1,-1, 1,-1,-1, 1,-1,-1, 1/
      DATA (NHEL(I, 478),I=1,9) / 1,-1, 1,-1,-1, 1,-1,-1,-1/
      DATA (NHEL(I, 479),I=1,9) / 1,-1, 1,-1,-1, 1,-1, 1, 1/
      DATA (NHEL(I, 480),I=1,9) / 1,-1, 1,-1,-1, 1,-1, 1,-1/
      DATA (NHEL(I, 481),I=1,9) / 1,-1, 1, 1, 1,-1, 1,-1, 1/
      DATA (NHEL(I, 482),I=1,9) / 1,-1, 1, 1, 1,-1, 1,-1,-1/
      DATA (NHEL(I, 483),I=1,9) / 1,-1, 1, 1, 1,-1, 1, 1, 1/
      DATA (NHEL(I, 484),I=1,9) / 1,-1, 1, 1, 1,-1, 1, 1,-1/
      DATA (NHEL(I, 485),I=1,9) / 1,-1, 1, 1, 1,-1,-1,-1, 1/
      DATA (NHEL(I, 486),I=1,9) / 1,-1, 1, 1, 1,-1,-1,-1,-1/
      DATA (NHEL(I, 487),I=1,9) / 1,-1, 1, 1, 1,-1,-1, 1, 1/
      DATA (NHEL(I, 488),I=1,9) / 1,-1, 1, 1, 1,-1,-1, 1,-1/
      DATA (NHEL(I, 489),I=1,9) / 1,-1, 1, 1, 1, 1, 1,-1, 1/
      DATA (NHEL(I, 490),I=1,9) / 1,-1, 1, 1, 1, 1, 1,-1,-1/
      DATA (NHEL(I, 491),I=1,9) / 1,-1, 1, 1, 1, 1, 1, 1, 1/
      DATA (NHEL(I, 492),I=1,9) / 1,-1, 1, 1, 1, 1, 1, 1,-1/
      DATA (NHEL(I, 493),I=1,9) / 1,-1, 1, 1, 1, 1,-1,-1, 1/
      DATA (NHEL(I, 494),I=1,9) / 1,-1, 1, 1, 1, 1,-1,-1,-1/
      DATA (NHEL(I, 495),I=1,9) / 1,-1, 1, 1, 1, 1,-1, 1, 1/
      DATA (NHEL(I, 496),I=1,9) / 1,-1, 1, 1, 1, 1,-1, 1,-1/
      DATA (NHEL(I, 497),I=1,9) / 1,-1, 1, 1,-1,-1, 1,-1, 1/
      DATA (NHEL(I, 498),I=1,9) / 1,-1, 1, 1,-1,-1, 1,-1,-1/
      DATA (NHEL(I, 499),I=1,9) / 1,-1, 1, 1,-1,-1, 1, 1, 1/
      DATA (NHEL(I, 500),I=1,9) / 1,-1, 1, 1,-1,-1, 1, 1,-1/
      DATA (NHEL(I, 501),I=1,9) / 1,-1, 1, 1,-1,-1,-1,-1, 1/
      DATA (NHEL(I, 502),I=1,9) / 1,-1, 1, 1,-1,-1,-1,-1,-1/
      DATA (NHEL(I, 503),I=1,9) / 1,-1, 1, 1,-1,-1,-1, 1, 1/
      DATA (NHEL(I, 504),I=1,9) / 1,-1, 1, 1,-1,-1,-1, 1,-1/
      DATA (NHEL(I, 505),I=1,9) / 1,-1, 1, 1,-1, 1, 1,-1, 1/
      DATA (NHEL(I, 506),I=1,9) / 1,-1, 1, 1,-1, 1, 1,-1,-1/
      DATA (NHEL(I, 507),I=1,9) / 1,-1, 1, 1,-1, 1, 1, 1, 1/
      DATA (NHEL(I, 508),I=1,9) / 1,-1, 1, 1,-1, 1, 1, 1,-1/
      DATA (NHEL(I, 509),I=1,9) / 1,-1, 1, 1,-1, 1,-1,-1, 1/
      DATA (NHEL(I, 510),I=1,9) / 1,-1, 1, 1,-1, 1,-1,-1,-1/
      DATA (NHEL(I, 511),I=1,9) / 1,-1, 1, 1,-1, 1,-1, 1, 1/
      DATA (NHEL(I, 512),I=1,9) / 1,-1, 1, 1,-1, 1,-1, 1,-1/

      GET_NHEL2 = NHEL(IPART, IABS(HEL))
      RETURN
      END





