C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Identity(2,1)
C     
      SUBROUTINE MP_FFS1_2(F1, S3, COUP, M2, W2,F2)
      IMPLICIT NONE
      COMPLEX*32 CI
      PARAMETER (CI=(0Q0,1Q0))
      COMPLEX*32 COUP
      COMPLEX*32 F1(*)
      COMPLEX*32 F2(8)
      REAL*16 M2
      COMPLEX*32 P2(0:3)
      COMPLEX*32 S3(*)
      REAL*16 W2
      COMPLEX*32 DENOM
      F2(1) = +F1(1)+S3(1)
      F2(2) = +F1(2)+S3(2)
      F2(3) = +F1(3)+S3(3)
      F2(4) = +F1(4)+S3(4)
      P2(0) = -F2(1)
      P2(1) = -F2(2)
      P2(2) = -F2(3)
      P2(3) = -F2(4)
      DENOM = COUP/(P2(0)**2-P2(1)**2-P2(2)**2-P2(3)**2 - M2 * (M2 -CI
     $ * W2))
      F2(5)= DENOM*CI * S3(5)*(F1(7)*(P2(0)-P2(3))+(F1(8)*(-P2(1)+CI
     $ *(P2(2)))+F1(5)*M2))
      F2(6)= DENOM*(-CI )* S3(5)*(F1(7)*(P2(1)+CI*(P2(2)))+(F1(8)*(
     $ -1Q0)*(P2(0)+P2(3))-F1(6)*M2))
      F2(7)= DENOM*(-CI )* S3(5)*(F1(5)*(-1Q0)*(P2(0)+P2(3))+(F1(6)*(
     $ -P2(1)+CI*(P2(2)))-F1(7)*M2))
      F2(8)= DENOM*CI * S3(5)*(F1(5)*(P2(1)+CI*(P2(2)))+(F1(6)*(P2(0)
     $ -P2(3))+F1(8)*M2))
      END


