ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of loop_sm-full'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_5 = ', GC_5
      WRITE(*,2) 'UVWfct_b_0_1eps = ', UVWFCT_B_0_1EPS
      WRITE(*,2) 'UVWfct_t_0_1eps = ', UVWFCT_T_0_1EPS
      WRITE(*,2) 'R2_dxtW = ', R2_DXTW
      WRITE(*,2) 'R2_sxtW = ', R2_SXTW
      WRITE(*,2) 'R2_bxtW = ', R2_BXTW
      WRITE(*,2) 'UVWfct_b_0 = ', UVWFCT_B_0
      WRITE(*,2) 'UVWfct_t_0 = ', UVWFCT_T_0
      WRITE(*,2) 'GC_11 = ', GC_11
      WRITE(*,2) 'GC_18 = ', GC_18
      WRITE(*,2) 'GC_19 = ', GC_19
      WRITE(*,2) 'GC_20 = ', GC_20
