      SUBROUTINE SMATRIX1(P, RHEL, RCOL, channel, IVEC, ANS, IHEL,
     $  ICOL)
C     
C     Generated by MadGraph5_aMC@NLO v. 3.6.6, 2025-10-30
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     MadGraph5_aMC@NLO for Madevent Version
C     
C     Returns amplitude squared summed/avg over colors
C     and helicities
C     for the point in phase space P(0:3,NEXTERNAL)
C     potentially times multi-channel weight
C     
C     Process: g mu+ > mu+ t t~ WEIGHTED<=5 @2
C     *   Decay: t > b w+ WEIGHTED<=2
C     *     Decay: w+ > c b~ WEIGHTED<=2
C     *   Decay: t~ > b~ w- WEIGHTED<=2
C     *     Decay: w- > e- ve~ WEIGHTED<=2
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      Include 'genps.inc'
      Include 'maxconfigs.inc'
      Include 'nexternal.inc'
      Include 'maxamps.inc'
      INTEGER                 NCOMB         
      PARAMETER (             NCOMB=135)
      INTEGER    NGRAPHS
      PARAMETER (NGRAPHS=6) 
      INTEGER    NDIAGS
      PARAMETER (NDIAGS=6) 
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL)
      double precision RHEL    !  random number for selecting helicity
      double precision RCOL    !  random number for selecting helicity
      integer channel    !  channel to keep for the multi-channel
      integer ivec    !  for using the correct coupling
C     
C     output argument
C     
      integer ihel, icol    !  selected helicity/color
      double precision ans 
C     
C     LOCAL VARIABLES 
C     
      INTEGER CONFSUB(MAXSPROC,LMAXCONFIGS)
      INCLUDE 'config_subproc_map.inc'
      INTEGER NHEL(0:NEXTERNAL,NCOMB)
      REAL*8 T
      REAL*8 R,SUMHEL,TS(NCOMB)
      INTEGER I,IDEN
      INTEGER JC(NEXTERNAL),II
      REAL*8 XTOT
      INTEGER  J, JJ
      double precision get_channel_cut
      external get_channel_cut

C     
C     GLOBAL VARIABLES
C     
      include '../../Source/vector.inc'    !  defines VECSIZE_MEMMAX
      DOUBLE PRECISION AMP2(MAXAMPS), JAMP2(0:MAXFLOW)


C     
C     INFORMATION TO WRITE THE HELICITY IN THE EVENT --not memory
C      efficient--
C     
      INTEGER NB_SPIN_STATE_in(2)
      common /nb_hel_state/ nb_spin_state_in

      REAL*8 POL(2)

      COMMON/TO_POLARIZATION/ POL
      double precision tmin_for_channel
      integer sde_strat    !  1 means standard single diagram enhancement strategy,
C     2 means approximation by the	denominator of the propagator
      common/TO_CHANNEL_STRAT/tmin_for_channel,	sde_strat

      INTEGER          ISUM_HEL
      LOGICAL                    MULTI_CHANNEL
      COMMON/TO_MATRIX/ISUM_HEL, MULTI_CHANNEL
      INTEGER MAPCONFIG(0:LMAXCONFIGS), ICONFIG
      COMMON/TO_MCONFIGS/MAPCONFIG, ICONFIG
      
      DATA (NHEL(I,1),I=0,9) /1,-1,-1, 1,-1,-1, 1, 1,-1, 1/
      DATA (NHEL(I,2),I=0,9) /3,-1,-1, 1,-1,-1, 1, 1, 1, 1/
      DATA (NHEL(I,3),I=0,9) /5,-1,-1, 1,-1,-1, 1,-1,-1, 1/
      DATA (NHEL(I,4),I=0,9) /9,-1,-1, 1,-1,-1,-1, 1,-1, 1/
      DATA (NHEL(I,5),I=0,9) /13,-1,-1, 1,-1,-1,-1,-1,-1, 1/
      DATA (NHEL(I,6),I=0,9) /17,-1,-1, 1,-1, 1, 1, 1,-1, 1/
      DATA (NHEL(I,7),I=0,9) /21,-1,-1, 1,-1, 1, 1,-1,-1, 1/
      DATA (NHEL(I,8),I=0,9) /25,-1,-1, 1,-1, 1,-1, 1,-1, 1/
      DATA (NHEL(I,9),I=0,9) /29,-1,-1, 1,-1, 1,-1,-1,-1, 1/
      DATA (NHEL(I,10),I=0,9) /33,-1,-1, 1, 1,-1, 1, 1,-1, 1/
      DATA (NHEL(I,11),I=0,9) /37,-1,-1, 1, 1,-1, 1,-1,-1, 1/
      DATA (NHEL(I,12),I=0,9) /41,-1,-1, 1, 1,-1,-1, 1,-1, 1/
      DATA (NHEL(I,13),I=0,9) /45,-1,-1, 1, 1,-1,-1,-1,-1, 1/
      DATA (NHEL(I,14),I=0,9) /49,-1,-1, 1, 1, 1, 1, 1,-1, 1/
      DATA (NHEL(I,15),I=0,9) /53,-1,-1, 1, 1, 1, 1,-1,-1, 1/
      DATA (NHEL(I,16),I=0,9) /57,-1,-1, 1, 1, 1,-1, 1,-1, 1/
      DATA (NHEL(I,17),I=0,9) /61,-1,-1, 1, 1, 1,-1,-1,-1, 1/
      DATA (NHEL(I,18),I=0,9) /65,-1,-1,-1,-1,-1, 1, 1,-1, 1/
      DATA (NHEL(I,19),I=0,9) /67,-1,-1,-1,-1,-1, 1, 1, 1, 1/
      DATA (NHEL(I,20),I=0,9) /69,-1,-1,-1,-1,-1, 1,-1,-1, 1/
      DATA (NHEL(I,21),I=0,9) /73,-1,-1,-1,-1,-1,-1, 1,-1, 1/
      DATA (NHEL(I,22),I=0,9) /75,-1,-1,-1,-1,-1,-1, 1, 1, 1/
      DATA (NHEL(I,23),I=0,9) /77,-1,-1,-1,-1,-1,-1,-1,-1, 1/
      DATA (NHEL(I,24),I=0,9) /81,-1,-1,-1,-1, 1, 1, 1,-1, 1/
      DATA (NHEL(I,25),I=0,9) /85,-1,-1,-1,-1, 1, 1,-1,-1, 1/
      DATA (NHEL(I,26),I=0,9) /89,-1,-1,-1,-1, 1,-1, 1,-1, 1/
      DATA (NHEL(I,27),I=0,9) /93,-1,-1,-1,-1, 1,-1,-1,-1, 1/
      DATA (NHEL(I,28),I=0,9) /97,-1,-1,-1, 1,-1, 1, 1,-1, 1/
      DATA (NHEL(I,29),I=0,9) /101,-1,-1,-1, 1,-1, 1,-1,-1, 1/
      DATA (NHEL(I,30),I=0,9) /105,-1,-1,-1, 1,-1,-1, 1,-1, 1/
      DATA (NHEL(I,31),I=0,9) /109,-1,-1,-1, 1,-1,-1,-1,-1, 1/
      DATA (NHEL(I,32),I=0,9) /113,-1,-1,-1, 1, 1, 1, 1,-1, 1/
      DATA (NHEL(I,33),I=0,9) /117,-1,-1,-1, 1, 1, 1,-1,-1, 1/
      DATA (NHEL(I,34),I=0,9) /121,-1,-1,-1, 1, 1,-1, 1,-1, 1/
      DATA (NHEL(I,35),I=0,9) /125,-1,-1,-1, 1, 1,-1,-1,-1, 1/
      DATA (NHEL(I,36),I=0,9) /129,-1, 1, 1,-1,-1, 1, 1,-1, 1/
      DATA (NHEL(I,37),I=0,9) /131,-1, 1, 1,-1,-1, 1, 1, 1, 1/
      DATA (NHEL(I,38),I=0,9) /133,-1, 1, 1,-1,-1, 1,-1,-1, 1/
      DATA (NHEL(I,39),I=0,9) /137,-1, 1, 1,-1,-1,-1, 1,-1, 1/
      DATA (NHEL(I,40),I=0,9) /139,-1, 1, 1,-1,-1,-1, 1, 1, 1/
      DATA (NHEL(I,41),I=0,9) /141,-1, 1, 1,-1,-1,-1,-1,-1, 1/
      DATA (NHEL(I,42),I=0,9) /145,-1, 1, 1,-1, 1, 1, 1,-1, 1/
      DATA (NHEL(I,43),I=0,9) /149,-1, 1, 1,-1, 1, 1,-1,-1, 1/
      DATA (NHEL(I,44),I=0,9) /153,-1, 1, 1,-1, 1,-1, 1,-1, 1/
      DATA (NHEL(I,45),I=0,9) /157,-1, 1, 1,-1, 1,-1,-1,-1, 1/
      DATA (NHEL(I,46),I=0,9) /161,-1, 1, 1, 1,-1, 1, 1,-1, 1/
      DATA (NHEL(I,47),I=0,9) /165,-1, 1, 1, 1,-1, 1,-1,-1, 1/
      DATA (NHEL(I,48),I=0,9) /169,-1, 1, 1, 1,-1,-1, 1,-1, 1/
      DATA (NHEL(I,49),I=0,9) /173,-1, 1, 1, 1,-1,-1,-1,-1, 1/
      DATA (NHEL(I,50),I=0,9) /177,-1, 1, 1, 1, 1, 1, 1,-1, 1/
      DATA (NHEL(I,51),I=0,9) /181,-1, 1, 1, 1, 1, 1,-1,-1, 1/
      DATA (NHEL(I,52),I=0,9) /185,-1, 1, 1, 1, 1,-1, 1,-1, 1/
      DATA (NHEL(I,53),I=0,9) /189,-1, 1, 1, 1, 1,-1,-1,-1, 1/
      DATA (NHEL(I,54),I=0,9) /193,-1, 1,-1,-1,-1, 1, 1,-1, 1/
      DATA (NHEL(I,55),I=0,9) /195,-1, 1,-1,-1,-1, 1, 1, 1, 1/
      DATA (NHEL(I,56),I=0,9) /197,-1, 1,-1,-1,-1, 1,-1,-1, 1/
      DATA (NHEL(I,57),I=0,9) /201,-1, 1,-1,-1,-1,-1, 1,-1, 1/
      DATA (NHEL(I,58),I=0,9) /205,-1, 1,-1,-1,-1,-1,-1,-1, 1/
      DATA (NHEL(I,59),I=0,9) /209,-1, 1,-1,-1, 1, 1, 1,-1, 1/
      DATA (NHEL(I,60),I=0,9) /213,-1, 1,-1,-1, 1, 1,-1,-1, 1/
      DATA (NHEL(I,61),I=0,9) /217,-1, 1,-1,-1, 1,-1, 1,-1, 1/
      DATA (NHEL(I,62),I=0,9) /221,-1, 1,-1,-1, 1,-1,-1,-1, 1/
      DATA (NHEL(I,63),I=0,9) /225,-1, 1,-1, 1,-1, 1, 1,-1, 1/
      DATA (NHEL(I,64),I=0,9) /229,-1, 1,-1, 1,-1, 1,-1,-1, 1/
      DATA (NHEL(I,65),I=0,9) /233,-1, 1,-1, 1,-1,-1, 1,-1, 1/
      DATA (NHEL(I,66),I=0,9) /237,-1, 1,-1, 1,-1,-1,-1,-1, 1/
      DATA (NHEL(I,67),I=0,9) /241,-1, 1,-1, 1, 1, 1, 1,-1, 1/
      DATA (NHEL(I,68),I=0,9) /245,-1, 1,-1, 1, 1, 1,-1,-1, 1/
      DATA (NHEL(I,69),I=0,9) /249,-1, 1,-1, 1, 1,-1, 1,-1, 1/
      DATA (NHEL(I,70),I=0,9) /257, 1,-1, 1,-1,-1, 1, 1,-1, 1/
      DATA (NHEL(I,71),I=0,9) /259, 1,-1, 1,-1,-1, 1, 1, 1, 1/
      DATA (NHEL(I,72),I=0,9) /261, 1,-1, 1,-1,-1, 1,-1,-1, 1/
      DATA (NHEL(I,73),I=0,9) /265, 1,-1, 1,-1,-1,-1, 1,-1, 1/
      DATA (NHEL(I,74),I=0,9) /269, 1,-1, 1,-1,-1,-1,-1,-1, 1/
      DATA (NHEL(I,75),I=0,9) /273, 1,-1, 1,-1, 1, 1, 1,-1, 1/
      DATA (NHEL(I,76),I=0,9) /277, 1,-1, 1,-1, 1, 1,-1,-1, 1/
      DATA (NHEL(I,77),I=0,9) /281, 1,-1, 1,-1, 1,-1, 1,-1, 1/
      DATA (NHEL(I,78),I=0,9) /285, 1,-1, 1,-1, 1,-1,-1,-1, 1/
      DATA (NHEL(I,79),I=0,9) /289, 1,-1, 1, 1,-1, 1, 1,-1, 1/
      DATA (NHEL(I,80),I=0,9) /293, 1,-1, 1, 1,-1, 1,-1,-1, 1/
      DATA (NHEL(I,81),I=0,9) /297, 1,-1, 1, 1,-1,-1, 1,-1, 1/
      DATA (NHEL(I,82),I=0,9) /301, 1,-1, 1, 1,-1,-1,-1,-1, 1/
      DATA (NHEL(I,83),I=0,9) /305, 1,-1, 1, 1, 1, 1, 1,-1, 1/
      DATA (NHEL(I,84),I=0,9) /309, 1,-1, 1, 1, 1, 1,-1,-1, 1/
      DATA (NHEL(I,85),I=0,9) /321, 1,-1,-1,-1,-1, 1, 1,-1, 1/
      DATA (NHEL(I,86),I=0,9) /323, 1,-1,-1,-1,-1, 1, 1, 1, 1/
      DATA (NHEL(I,87),I=0,9) /325, 1,-1,-1,-1,-1, 1,-1,-1, 1/
      DATA (NHEL(I,88),I=0,9) /329, 1,-1,-1,-1,-1,-1, 1,-1, 1/
      DATA (NHEL(I,89),I=0,9) /333, 1,-1,-1,-1,-1,-1,-1,-1, 1/
      DATA (NHEL(I,90),I=0,9) /337, 1,-1,-1,-1, 1, 1, 1,-1, 1/
      DATA (NHEL(I,91),I=0,9) /341, 1,-1,-1,-1, 1, 1,-1,-1, 1/
      DATA (NHEL(I,92),I=0,9) /345, 1,-1,-1,-1, 1,-1, 1,-1, 1/
      DATA (NHEL(I,93),I=0,9) /349, 1,-1,-1,-1, 1,-1,-1,-1, 1/
      DATA (NHEL(I,94),I=0,9) /353, 1,-1,-1, 1,-1, 1, 1,-1, 1/
      DATA (NHEL(I,95),I=0,9) /357, 1,-1,-1, 1,-1, 1,-1,-1, 1/
      DATA (NHEL(I,96),I=0,9) /361, 1,-1,-1, 1,-1,-1, 1,-1, 1/
      DATA (NHEL(I,97),I=0,9) /365, 1,-1,-1, 1,-1,-1,-1,-1, 1/
      DATA (NHEL(I,98),I=0,9) /369, 1,-1,-1, 1, 1, 1, 1,-1, 1/
      DATA (NHEL(I,99),I=0,9) /373, 1,-1,-1, 1, 1, 1,-1,-1, 1/
      DATA (NHEL(I,100),I=0,9) /377, 1,-1,-1, 1, 1,-1, 1,-1, 1/
      DATA (NHEL(I,101),I=0,9) /385, 1, 1, 1,-1,-1, 1, 1,-1, 1/
      DATA (NHEL(I,102),I=0,9) /387, 1, 1, 1,-1,-1, 1, 1, 1, 1/
      DATA (NHEL(I,103),I=0,9) /389, 1, 1, 1,-1,-1, 1,-1,-1, 1/
      DATA (NHEL(I,104),I=0,9) /393, 1, 1, 1,-1,-1,-1, 1,-1, 1/
      DATA (NHEL(I,105),I=0,9) /395, 1, 1, 1,-1,-1,-1, 1, 1, 1/
      DATA (NHEL(I,106),I=0,9) /397, 1, 1, 1,-1,-1,-1,-1,-1, 1/
      DATA (NHEL(I,107),I=0,9) /401, 1, 1, 1,-1, 1, 1, 1,-1, 1/
      DATA (NHEL(I,108),I=0,9) /405, 1, 1, 1,-1, 1, 1,-1,-1, 1/
      DATA (NHEL(I,109),I=0,9) /409, 1, 1, 1,-1, 1,-1, 1,-1, 1/
      DATA (NHEL(I,110),I=0,9) /413, 1, 1, 1,-1, 1,-1,-1,-1, 1/
      DATA (NHEL(I,111),I=0,9) /417, 1, 1, 1, 1,-1, 1, 1,-1, 1/
      DATA (NHEL(I,112),I=0,9) /421, 1, 1, 1, 1,-1, 1,-1,-1, 1/
      DATA (NHEL(I,113),I=0,9) /425, 1, 1, 1, 1,-1,-1, 1,-1, 1/
      DATA (NHEL(I,114),I=0,9) /429, 1, 1, 1, 1,-1,-1,-1,-1, 1/
      DATA (NHEL(I,115),I=0,9) /433, 1, 1, 1, 1, 1, 1, 1,-1, 1/
      DATA (NHEL(I,116),I=0,9) /437, 1, 1, 1, 1, 1, 1,-1,-1, 1/
      DATA (NHEL(I,117),I=0,9) /441, 1, 1, 1, 1, 1,-1, 1,-1, 1/
      DATA (NHEL(I,118),I=0,9) /445, 1, 1, 1, 1, 1,-1,-1,-1, 1/
      DATA (NHEL(I,119),I=0,9) /449, 1, 1,-1,-1,-1, 1, 1,-1, 1/
      DATA (NHEL(I,120),I=0,9) /451, 1, 1,-1,-1,-1, 1, 1, 1, 1/
      DATA (NHEL(I,121),I=0,9) /453, 1, 1,-1,-1,-1, 1,-1,-1, 1/
      DATA (NHEL(I,122),I=0,9) /457, 1, 1,-1,-1,-1,-1, 1,-1, 1/
      DATA (NHEL(I,123),I=0,9) /461, 1, 1,-1,-1,-1,-1,-1,-1, 1/
      DATA (NHEL(I,124),I=0,9) /465, 1, 1,-1,-1, 1, 1, 1,-1, 1/
      DATA (NHEL(I,125),I=0,9) /469, 1, 1,-1,-1, 1, 1,-1,-1, 1/
      DATA (NHEL(I,126),I=0,9) /473, 1, 1,-1,-1, 1,-1, 1,-1, 1/
      DATA (NHEL(I,127),I=0,9) /477, 1, 1,-1,-1, 1,-1,-1,-1, 1/
      DATA (NHEL(I,128),I=0,9) /481, 1, 1,-1, 1,-1, 1, 1,-1, 1/
      DATA (NHEL(I,129),I=0,9) /485, 1, 1,-1, 1,-1, 1,-1,-1, 1/
      DATA (NHEL(I,130),I=0,9) /489, 1, 1,-1, 1,-1,-1, 1,-1, 1/
      DATA (NHEL(I,131),I=0,9) /493, 1, 1,-1, 1,-1,-1,-1,-1, 1/
      DATA (NHEL(I,132),I=0,9) /497, 1, 1,-1, 1, 1, 1, 1,-1, 1/
      DATA (NHEL(I,133),I=0,9) /501, 1, 1,-1, 1, 1, 1,-1,-1, 1/
      DATA (NHEL(I,134),I=0,9) /505, 1, 1,-1, 1, 1,-1, 1,-1, 1/
      DATA (NHEL(I,135),I=0,9) /509, 1, 1,-1, 1, 1,-1,-1,-1, 1/
      DATA IDEN/32/

C     ----------
C     BEGIN CODE
C     ----------

      DO I=1,NEXTERNAL
        JC(I) = +1
      ENDDO

      IF (multi_channel) THEN
        DO I=1,NDIAGS
          AMP2(I)=0D0
        ENDDO
      ENDIF
      JAMP2(0)=1
      DO I=1,INT(JAMP2(0))
        JAMP2(I)=0D0
      ENDDO


      ANS = 0D0

      TS(:) = 0d0

      call MATRIX1(P ,JC(1), TS, AMP2, JAMP2, IVEC)
      DO I=1,NCOMB     
        T=TS(I)  
        DO JJ=1,nincoming
          IF(POL(JJ).NE.1d0.AND.NHEL(JJ,I).EQ.INT(SIGN(1d0,POL(JJ))))
     $      THEN
            T=T*ABS(POL(JJ))*NB_SPIN_STATE_IN(JJ)/2d0    !  NB_SPIN_STATE(JJ)/2d0 is added for polarised beam
          ELSE IF(POL(JJ).NE.1d0)THEN
            T=T*(2d0-ABS(POL(JJ)))*NB_SPIN_STATE_IN(JJ)/2d0
          ENDIF
        ENDDO
        ANS=ANS+DABS(T)
        TS(I)=T
      ENDDO

      IF (ANS.ne.0d0) THEN
        SUMHEL=0d0
        DO I=1,NCOMB
          SUMHEL=SUMHEL+DABS(TS(I))/ANS
          IF(RHEL.LT.SUMHEL)THEN
            IHEL = NHEL(0,I)    !  this returns the id of the helicity before helicity recycling
C           WRITE(HEL_BUFF,'(20i5)')(NHEL(II,I),II=1,NEXTERNAL)
C           Set right sign for ANS, based on sign of chosen helicity
            ANS=DSIGN(ANS,TS(I))
            GOTO 10
          ENDIF
        ENDDO
 10     CONTINUE   
      ENDIF
      IF (MULTI_CHANNEL) THEN
        XTOT=0D0
        DO I=1,LMAXCONFIGS
          J = CONFSUB(1, I)
          if (J.ne.0)then
            if (sde_strat.eq.1)then
              AMP2(J) = AMP2(J) * GET_CHANNEL_CUT(P, I)
            else
              AMP2(J) = GET_CHANNEL_CUT(P, I)
            endif
            XTOT=XTOT+AMP2(J)

          endif
        ENDDO
        IF (XTOT.NE.0D0) THEN
          ANS=ANS*AMP2(channel)/XTOT
        ELSE IF(ANS.ne.0d0) THEN
          write(*,*) 'Problem in the multi-channeling. All amp2 are'
     $     //' zero but not the total matrix-element'
          stop 1
        ENDIF
      ENDIF
      ANS=ANS/DBLE(IDEN)

      call select_color(rcol, jamp2, iconfig,1,  icol)

      END


      Subroutine  MATRIX1(P,IC, TS, AMP2, JAMP2, IVEC)
C     
C     Generated by MadGraph5_aMC@NLO v. 3.6.6, 2025-10-30
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     Returns amplitude squared summed/avg over colors
C     for the point with external lines W(0:6,NEXTERNAL)
C     
C     Process: g mu+ > mu+ t t~ WEIGHTED<=5 @2
C     *   Decay: t > b w+ WEIGHTED<=2
C     *     Decay: w+ > c b~ WEIGHTED<=2
C     *   Decay: t~ > b~ w- WEIGHTED<=2
C     *     Decay: w- > e- ve~ WEIGHTED<=2
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NGRAPHS
      PARAMETER (NGRAPHS=6) 
      include 'genps.inc'
      include 'nexternal.inc'
      include 'maxamps.inc'
      INTEGER    NWAVEFUNCS,     NCOLOR
      PARAMETER (NWAVEFUNCS=68, NCOLOR=1) 
      REAL*8     ZERO
      PARAMETER (ZERO=0D0)
      COMPLEX*16 IMAG1
      PARAMETER (IMAG1=(0D0,1D0))
      INTEGER NAMPSO, NSQAMPSO
      PARAMETER (NAMPSO=1, NSQAMPSO=1)
      LOGICAL CHOSEN_SO_CONFIGS(NSQAMPSO)
      DATA CHOSEN_SO_CONFIGS/.TRUE./
      SAVE CHOSEN_SO_CONFIGS
      INTEGER                 NCOMB         
      PARAMETER (             NCOMB=135)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL)
      INTEGER NHEL(NEXTERNAL), IC(NEXTERNAL)
      REAL*8 TS(NCOMB)
      INTEGER IVEC
C     
C     LOCAL VARIABLES 
C     
      INTEGER I,J,M,N,K
      COMPLEX*16 ZTEMP,TMP_JAMP(0)
      COMPLEX*16 TMP(6)
      INTEGER CF(NCOLOR*(NCOLOR+1))
      INTEGER DENOM, CF_INDEX
      COMPLEX*16 AMP(NCOMB,NGRAPHS), JAMP(NCOLOR,NAMPSO)
      COMPLEX*16 W(6,NWAVEFUNCS)
C     Needed for v4 models
      COMPLEX*16 DUM0,DUM1
      DATA DUM0, DUM1/(0d0, 0d0), (1d0, 0d0)/

      double precision fk_mdl_WZ 
      double precision fk_mdl_WT 
      double precision fk_mdl_WH 
      double precision fk_mdl_WW 
      double precision fk_ZERO 
      save fk_mdl_WZ 
      save fk_mdl_WT 
      save fk_mdl_WH 
      save fk_mdl_WW 
      save fk_ZERO 

      logical first
      data first /.true./
      save first
C     
C     FUNCTION
C     
      INTEGER SQSOINDEX1

C     
C     GLOBAL VARIABLES
C     
      include '../../Source/vector.inc'    !  defines VECSIZE_MEMMAX
      Double Precision amp2(maxamps), jamp2(0:maxflow)
      include 'coupl.inc'    !  needs VECSIZE_MEMMAX (defined in vector.inc)

      double precision tmin_for_channel
      integer sde_strat    !  1 means standard single diagram enhancement strategy,
C     2 means approximation by the	denominator of the propagator
      common/TO_CHANNEL_STRAT/tmin_for_channel,	sde_strat

      double precision small_width_treatment
      common/narrow_width/small_width_treatment
C     
C     COLOR DATA
C     
      DATA Denom/1/
      DATA (CF(i),i=  1,  1) /12/
C     1 T(1,4,7) T(5,6)
C     ----------
C     BEGIN CODE
C     ----------
      if (first) then
        first=.false.
        fk_zero = 0d0
        IF(mdl_WH.ne.0d0) then 
          fk_mdl_WH = SIGN(MAX(ABS(mdl_WH), ABS(mdl_MH
     $     *small_width_treatment)), mdl_WH) 
        else 
          fk_mdl_WH = 0d0
        endif

        IF(mdl_WT.ne.0d0) then 
          fk_mdl_WT = SIGN(MAX(ABS(mdl_WT), ABS(mdl_MT
     $     *small_width_treatment)), mdl_WT) 
        else 
          fk_mdl_WT = 0d0
        endif

        IF(mdl_WW.ne.0d0) then 
          fk_mdl_WW = SIGN(MAX(ABS(mdl_WW), ABS(mdl_MW
     $     *small_width_treatment)), mdl_WW) 
        else 
          fk_mdl_WW = 0d0
        endif

        IF(mdl_WZ.ne.0d0) then 
          fk_mdl_WZ = SIGN(MAX(ABS(mdl_WZ), ABS(mdl_MZ
     $     *small_width_treatment)), mdl_WZ) 
        else 
          fk_mdl_WZ = 0d0
        endif

      endif
      AMP(:,:) = (0d0,0d0)
            CALL VXXXXX(P(0,1),ZERO,+1,-1*IC(1),W(1,1))  !  count 11
      CALL VXXXXX(P(0,1),ZERO,-1,-1*IC(1),W(1,2))  !  count 11
      CALL OXXXXX(P(0,2),MDL_MM,+1,-1*IC(2),W(1,3))  !  count 6
      CALL OXXXXX(P(0,2),MDL_MM,-1,-1*IC(2),W(1,4))  !  count 6
      CALL IXXXXX(P(0,3),MDL_MM,+1,-1*IC(3),W(1,5))  !  count 6
      CALL IXXXXX(P(0,3),MDL_MM,-1,-1*IC(3),W(1,6))  !  count 6
      CALL OXXXXX(P(0,4),MDL_MB,+1,+1*IC(4),W(1,7))  !  count 4
      CALL OXXXXX(P(0,4),MDL_MB,-1,+1*IC(4),W(1,8))  !  count 4
      CALL OXXXXX(P(0,5),MDL_MC,+1,+1*IC(5),W(1,9))  !  count 2
      CALL OXXXXX(P(0,5),MDL_MC,-1,+1*IC(5),W(1,10))  !  count 2
      CALL IXXXXX(P(0,6),MDL_MB,+1,-1*IC(6),W(1,11))  !  count 2
      CALL IXXXXX(P(0,6),MDL_MB,-1,-1*IC(6),W(1,12))  !  count 2
      CALL FFV2_3(W(1,11),W(1,9),GC_46,MDL_MW,FK_MDL_WW,W(1,13))  !  count 2
      CALL FFV2_3(W(1,11),W(1,10),GC_46,MDL_MW,FK_MDL_WW,W(1,14))  !  count 2
      CALL FFV2_3(W(1,12),W(1,9),GC_46,MDL_MW,FK_MDL_WW,W(1,15))  !  count 2
      CALL FFV2_3(W(1,12),W(1,10),GC_46,MDL_MW,FK_MDL_WW,W(1,16))  !  count 2
      CALL FFV2_1(W(1,7),W(1,13),GC_108,MDL_MT,FK_MDL_WT,W(1,17))  !  count 50
      CALL FFV2_1(W(1,7),W(1,14),GC_108,MDL_MT,FK_MDL_WT,W(1,18))  !  count 50
      CALL FFV2_1(W(1,7),W(1,15),GC_108,MDL_MT,FK_MDL_WT,W(1,19))  !  count 38
      CALL FFV2_1(W(1,7),W(1,16),GC_108,MDL_MT,FK_MDL_WT,W(1,20))  !  count 50
      CALL FFV2_1(W(1,8),W(1,13),GC_108,MDL_MT,FK_MDL_WT,W(1,21))  !  count 50
      CALL FFV2_1(W(1,8),W(1,14),GC_108,MDL_MT,FK_MDL_WT,W(1,22))  !  count 74
      CALL FFV2_1(W(1,8),W(1,15),GC_108,MDL_MT,FK_MDL_WT,W(1,23))  !  count 50
      CALL FFV2_1(W(1,8),W(1,16),GC_108,MDL_MT,FK_MDL_WT,W(1,24))  !  count 59
      CALL IXXXXX(P(0,7),MDL_MB,+1,-1*IC(7),W(1,25))  !  count 2
      CALL IXXXXX(P(0,7),MDL_MB,-1,-1*IC(7),W(1,26))  !  count 1
      CALL OXXXXX(P(0,8),MDL_ME,+1,+1*IC(8),W(1,27))  !  count 1
      CALL OXXXXX(P(0,8),MDL_ME,-1,+1*IC(8),W(1,28))  !  count 1
      CALL IXXXXX(P(0,9),ZERO,+1,-1*IC(9),W(1,29))  !  count 2
      CALL FFV2_3(W(1,29),W(1,27),GC_40,MDL_MW,FK_MDL_WW,W(1,30))  !  count 1
      CALL FFV2_3(W(1,29),W(1,28),GC_40,MDL_MW,FK_MDL_WW,W(1,31))  !  count 2
      CALL FFV2_2(W(1,25),W(1,30),GC_49,MDL_MT,FK_MDL_WT,W(1,32))  !  count 35
      CALL FFV2_2(W(1,25),W(1,31),GC_49,MDL_MT,FK_MDL_WT,W(1,33))  !  count 191
      CALL FFV2_2(W(1,26),W(1,31),GC_49,MDL_MT,FK_MDL_WT,W(1,34))  !  count 185
      CALL FFV1_1(W(1,17),W(1,1),GC_11(IVEC),MDL_MT,ZERO,W(1,35))  !  count 24
      CALL FFV1_1(W(1,17),W(1,2),GC_11(IVEC),MDL_MT,ZERO,W(1,36))  !  count 24
      CALL FFV1_1(W(1,18),W(1,1),GC_11(IVEC),MDL_MT,ZERO,W(1,37))  !  count 24
      CALL FFV1_1(W(1,18),W(1,2),GC_11(IVEC),MDL_MT,ZERO,W(1,38))  !  count 24
      CALL FFV1_1(W(1,19),W(1,1),GC_11(IVEC),MDL_MT,ZERO,W(1,39))  !  count 15
      CALL FFV1_1(W(1,19),W(1,2),GC_11(IVEC),MDL_MT,ZERO,W(1,40))  !  count 21
      CALL FFV1_1(W(1,20),W(1,1),GC_11(IVEC),MDL_MT,ZERO,W(1,41))  !  count 24
      CALL FFV1_1(W(1,20),W(1,2),GC_11(IVEC),MDL_MT,ZERO,W(1,42))  !  count 24
      CALL FFV1_1(W(1,21),W(1,1),GC_11(IVEC),MDL_MT,ZERO,W(1,43))  !  count 24
      CALL FFV1_1(W(1,21),W(1,2),GC_11(IVEC),MDL_MT,ZERO,W(1,44))  !  count 24
      CALL FFV1_1(W(1,22),W(1,1),GC_11(IVEC),MDL_MT,ZERO,W(1,45))  !  count 36
      CALL FFV1_1(W(1,22),W(1,2),GC_11(IVEC),MDL_MT,ZERO,W(1,46))  !  count 36
      CALL FFV1_1(W(1,23),W(1,1),GC_11(IVEC),MDL_MT,ZERO,W(1,47))  !  count 24
      CALL FFV1_1(W(1,23),W(1,2),GC_11(IVEC),MDL_MT,ZERO,W(1,48))  !  count 24
      CALL FFV1_1(W(1,24),W(1,1),GC_11(IVEC),MDL_MT,ZERO,W(1,49))  !  count 27
      CALL FFV1_1(W(1,24),W(1,2),GC_11(IVEC),MDL_MT,ZERO,W(1,50))  !  count 30
      CALL FFV1P0_3(W(1,5),W(1,3),GC_3,ZERO,FK_ZERO,W(1,51))  !  count 72
      CALL FFV1P0_3(W(1,5),W(1,4),GC_3,ZERO,FK_ZERO,W(1,52))  !  count 64
      CALL FFV1P0_3(W(1,6),W(1,3),GC_3,ZERO,FK_ZERO,W(1,53))  !  count 66
      CALL FFV1P0_3(W(1,6),W(1,4),GC_3,ZERO,FK_ZERO,W(1,54))  !  count 68
      CALL FFV1P1N_2(W(1,32), W(1,51), GC_2, TMP(1))
      call CombineAmp(4,
     & (/102,37,105,40/), 
     & (/45,46,49,50/),
     & TMP, W, AMP(1,1))
      CALL FFV1P1N_2(W(1,32), W(1,52), GC_2, TMP(1))
      call CombineAmp(2,
     & (/71,2/), 
     & (/45,46/),
     & TMP, W, AMP(1,1))
      CALL FFV1P1N_2(W(1,32), W(1,53), GC_2, TMP(1))
      call CombineAmp(2,
     & (/120,55/), 
     & (/45,46/),
     & TMP, W, AMP(1,1))
      CALL FFV1P1N_2(W(1,32), W(1,54), GC_2, TMP(1))
      call CombineAmp(3,
     & (/86,19,22/), 
     & (/45,46,50/),
     & TMP, W, AMP(1,1))
      CALL FFV1P1N_2(W(1,33), W(1,51), GC_2, TMP(1))
      call CombineAmp(16,
     & (/115,50,111,46,117,52,113,48,107,42,101,36,109,44,104,39/), 
     & (/35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50/),
     & TMP, W, AMP(1,1))
      CALL FFV1P1N_2(W(1,33), W(1,52), GC_2, TMP(1))
      call CombineAmp(15,
     & (/83,14,79,10,16,81,12,75,6,70,1,77,8,73,4/), 
     & (/35,36,37,38,40,41,42,43,44,45,46,47,48,49,50/),
     & TMP, W, AMP(1,1))
      CALL FFV1P1N_2(W(1,33), W(1,53), GC_2, TMP(1))
      call CombineAmp(16,
     & (/132,67,128,63,134,69,130,65,124,59,119,54,126,61,122,57/), 
     & (/35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50/),
     & TMP, W, AMP(1,1))
      CALL FFV1P1N_2(W(1,33), W(1,54), GC_2, TMP(1))
      call CombineAmp(16,
     & (/98,32,94,28,100,34,96,30,90,24,85,18,92,26,88,21/), 
     & (/35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50/),
     & TMP, W, AMP(1,1))
      CALL FFV1P1N_2(W(1,34), W(1,51), GC_2, TMP(1))
      call CombineAmp(16,
     & (/116,51,112,47,118,53,114,49,108,43,103,38,110,45,106,41/), 
     & (/35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50/),
     & TMP, W, AMP(1,1))
      CALL FFV1P1N_2(W(1,34), W(1,52), GC_2, TMP(1))
      call CombineAmp(15,
     & (/84,15,80,11,17,82,13,76,7,72,3,78,9,74,5/), 
     & (/35,36,37,38,40,41,42,43,44,45,46,47,48,49,50/),
     & TMP, W, AMP(1,1))
      CALL FFV1P1N_2(W(1,34), W(1,53), GC_2, TMP(1))
      call CombineAmp(15,
     & (/133,68,129,64,135,131,66,125,60,121,56,127,62,123,58/), 
     & (/35,36,37,38,39,41,42,43,44,45,46,47,48,49,50/),
     & TMP, W, AMP(1,1))
      CALL FFV1P1N_2(W(1,34), W(1,54), GC_2, TMP(1))
      call CombineAmp(15,
     & (/99,33,95,29,35,97,31,91,25,87,20,93,27,89,23/), 
     & (/35,36,37,38,40,41,42,43,44,45,46,47,48,49,50/),
     & TMP, W, AMP(1,1))  !  count 1
      CALL FFS4_3(W(1,5),W(1,3),GC_93,MDL_MH,ZERO,W(1,55))  !  count 72
      CALL FFS4_3(W(1,5),W(1,4),GC_93,MDL_MH,ZERO,W(1,56))  !  count 64
      CALL FFS4_3(W(1,6),W(1,3),GC_93,MDL_MH,ZERO,W(1,57))  !  count 66
      CALL FFS4_3(W(1,6),W(1,4),GC_93,MDL_MH,ZERO,W(1,58))  !  count 68
      CALL FFS4P1N_2(W(1,32), W(1,55), GC_94, TMP(1))
      call CombineAmp(4,
     & (/102,37,105,40/), 
     & (/45,46,49,50/),
     & TMP, W, AMP(1,2))
      CALL FFS4P1N_2(W(1,32), W(1,56), GC_94, TMP(1))
      call CombineAmp(2,
     & (/71,2/), 
     & (/45,46/),
     & TMP, W, AMP(1,2))
      CALL FFS4P1N_2(W(1,32), W(1,57), GC_94, TMP(1))
      call CombineAmp(2,
     & (/120,55/), 
     & (/45,46/),
     & TMP, W, AMP(1,2))
      CALL FFS4P1N_2(W(1,32), W(1,58), GC_94, TMP(1))
      call CombineAmp(3,
     & (/86,19,22/), 
     & (/45,46,50/),
     & TMP, W, AMP(1,2))
      CALL FFS4P1N_2(W(1,33), W(1,55), GC_94, TMP(1))
      call CombineAmp(16,
     & (/115,50,111,46,117,52,113,48,107,42,101,36,109,44,104,39/), 
     & (/35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50/),
     & TMP, W, AMP(1,2))
      CALL FFS4P1N_2(W(1,33), W(1,56), GC_94, TMP(1))
      call CombineAmp(15,
     & (/83,14,79,10,16,81,12,75,6,70,1,77,8,73,4/), 
     & (/35,36,37,38,40,41,42,43,44,45,46,47,48,49,50/),
     & TMP, W, AMP(1,2))
      CALL FFS4P1N_2(W(1,33), W(1,57), GC_94, TMP(1))
      call CombineAmp(16,
     & (/132,67,128,63,134,69,130,65,124,59,119,54,126,61,122,57/), 
     & (/35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50/),
     & TMP, W, AMP(1,2))
      CALL FFS4P1N_2(W(1,33), W(1,58), GC_94, TMP(1))
      call CombineAmp(16,
     & (/98,32,94,28,100,34,96,30,90,24,85,18,92,26,88,21/), 
     & (/35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50/),
     & TMP, W, AMP(1,2))
      CALL FFS4P1N_2(W(1,34), W(1,55), GC_94, TMP(1))
      call CombineAmp(16,
     & (/116,51,112,47,118,53,114,49,108,43,103,38,110,45,106,41/), 
     & (/35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50/),
     & TMP, W, AMP(1,2))
      CALL FFS4P1N_2(W(1,34), W(1,56), GC_94, TMP(1))
      call CombineAmp(15,
     & (/84,15,80,11,17,82,13,76,7,72,3,78,9,74,5/), 
     & (/35,36,37,38,40,41,42,43,44,45,46,47,48,49,50/),
     & TMP, W, AMP(1,2))
      CALL FFS4P1N_2(W(1,34), W(1,57), GC_94, TMP(1))
      call CombineAmp(15,
     & (/133,68,129,64,135,131,66,125,60,121,56,127,62,123,58/), 
     & (/35,36,37,38,39,41,42,43,44,45,46,47,48,49,50/),
     & TMP, W, AMP(1,2))
      CALL FFS4P1N_2(W(1,34), W(1,58), GC_94, TMP(1))
      call CombineAmp(15,
     & (/99,33,95,29,35,97,31,91,25,87,20,93,27,89,23/), 
     & (/35,36,37,38,40,41,42,43,44,45,46,47,48,49,50/),
     & TMP, W, AMP(1,2))  !  count 1
      CALL FFV2_4_3(W(1,5),W(1,3),GC_50,GC_59,MDL_MZ,ZERO,W(1,59))  !  count 72
      CALL FFV2_4_3(W(1,5),W(1,4),GC_50,GC_59,MDL_MZ,ZERO,W(1,60))  !  count 64
      CALL FFV2_4_3(W(1,6),W(1,3),GC_50,GC_59,MDL_MZ,ZERO,W(1,61))  !  count 66
      CALL FFV2_4_3(W(1,6),W(1,4),GC_50,GC_59,MDL_MZ,ZERO,W(1,62))  !  count 68
      CALL FFV2_5P1N_2(W(1,32), W(1,59), GC_51, GC_58, TMP(1))
      call CombineAmp(4,
     & (/102,37,105,40/), 
     & (/45,46,49,50/),
     & TMP, W, AMP(1,3))
      CALL FFV2_5P1N_2(W(1,32), W(1,60), GC_51, GC_58, TMP(1))
      call CombineAmp(2,
     & (/71,2/), 
     & (/45,46/),
     & TMP, W, AMP(1,3))
      CALL FFV2_5P1N_2(W(1,32), W(1,61), GC_51, GC_58, TMP(1))
      call CombineAmp(2,
     & (/120,55/), 
     & (/45,46/),
     & TMP, W, AMP(1,3))
      CALL FFV2_5P1N_2(W(1,32), W(1,62), GC_51, GC_58, TMP(1))
      call CombineAmp(3,
     & (/86,19,22/), 
     & (/45,46,50/),
     & TMP, W, AMP(1,3))
      CALL FFV2_5P1N_2(W(1,33), W(1,59), GC_51, GC_58, TMP(1))
      call CombineAmp(16,
     & (/115,50,111,46,117,52,113,48,107,42,101,36,109,44,104,39/), 
     & (/35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50/),
     & TMP, W, AMP(1,3))
      CALL FFV2_5P1N_2(W(1,33), W(1,60), GC_51, GC_58, TMP(1))
      call CombineAmp(15,
     & (/83,14,79,10,16,81,12,75,6,70,1,77,8,73,4/), 
     & (/35,36,37,38,40,41,42,43,44,45,46,47,48,49,50/),
     & TMP, W, AMP(1,3))
      CALL FFV2_5P1N_2(W(1,33), W(1,61), GC_51, GC_58, TMP(1))
      call CombineAmp(16,
     & (/132,67,128,63,134,69,130,65,124,59,119,54,126,61,122,57/), 
     & (/35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50/),
     & TMP, W, AMP(1,3))
      CALL FFV2_5P1N_2(W(1,33), W(1,62), GC_51, GC_58, TMP(1))
      call CombineAmp(16,
     & (/98,32,94,28,100,34,96,30,90,24,85,18,92,26,88,21/), 
     & (/35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50/),
     & TMP, W, AMP(1,3))
      CALL FFV2_5P1N_2(W(1,34), W(1,59), GC_51, GC_58, TMP(1))
      call CombineAmp(16,
     & (/116,51,112,47,118,53,114,49,108,43,103,38,110,45,106,41/), 
     & (/35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50/),
     & TMP, W, AMP(1,3))
      CALL FFV2_5P1N_2(W(1,34), W(1,60), GC_51, GC_58, TMP(1))
      call CombineAmp(15,
     & (/84,15,80,11,17,82,13,76,7,72,3,78,9,74,5/), 
     & (/35,36,37,38,40,41,42,43,44,45,46,47,48,49,50/),
     & TMP, W, AMP(1,3))
      CALL FFV2_5P1N_2(W(1,34), W(1,61), GC_51, GC_58, TMP(1))
      call CombineAmp(15,
     & (/133,68,129,64,135,131,66,125,60,121,56,127,62,123,58/), 
     & (/35,36,37,38,39,41,42,43,44,45,46,47,48,49,50/),
     & TMP, W, AMP(1,3))
      CALL FFV2_5P1N_2(W(1,34), W(1,62), GC_51, GC_58, TMP(1))
      call CombineAmp(15,
     & (/99,33,95,29,35,97,31,91,25,87,20,93,27,89,23/), 
     & (/35,36,37,38,40,41,42,43,44,45,46,47,48,49,50/),
     & TMP, W, AMP(1,3))  !  count 1
      CALL FFV1_2(W(1,32),W(1,1),GC_11(IVEC),MDL_MT,ZERO,W(1,63))  !  count 15
      CALL FFV1_2(W(1,32),W(1,2),GC_11(IVEC),MDL_MT,ZERO,W(1,64))  !  count 18
      CALL FFV1_2(W(1,33),W(1,1),GC_11(IVEC),MDL_MT,ZERO,W(1,65))  !  count 93
      CALL FFV1_2(W(1,33),W(1,2),GC_11(IVEC),MDL_MT,ZERO,W(1,66))  !  count 96
      CALL FFV1_2(W(1,34),W(1,1),GC_11(IVEC),MDL_MT,ZERO,W(1,67))  !  count 90
      CALL FFV1_2(W(1,34),W(1,2),GC_11(IVEC),MDL_MT,ZERO,W(1,68))  !  count 93
      CALL FFV1P1N_2(W(1,63), W(1,51), GC_2, TMP(1))
      call CombineAmp(2,
     & (/102,105/), 
     & (/22,24/),
     & TMP, W, AMP(1,4))
      CALL FFV1_0(W(1,63),W(1,22),W(1,52),GC_2,AMP(71,4))
      CALL FFV1_0(W(1,63),W(1,22),W(1,53),GC_2,AMP(120,4))
      CALL FFV1_0(W(1,63),W(1,22),W(1,54),GC_2,AMP(86,4))
      CALL FFV1P1N_2(W(1,64), W(1,51), GC_2, TMP(1))
      call CombineAmp(2,
     & (/37,40/), 
     & (/22,24/),
     & TMP, W, AMP(1,4))
      CALL FFV1_0(W(1,64),W(1,22),W(1,52),GC_2,AMP(2,4))
      CALL FFV1_0(W(1,64),W(1,22),W(1,53),GC_2,AMP(55,4))
      CALL FFV1P1N_2(W(1,64), W(1,54), GC_2, TMP(1))
      call CombineAmp(2,
     & (/19,22/), 
     & (/22,24/),
     & TMP, W, AMP(1,4))
      CALL FFV1P1N_2(W(1,65), W(1,51), GC_2, TMP(1))
      call CombineAmp(8,
     & (/115,111,117,113,107,101,109,104/), 
     & (/17,18,19,20,21,22,23,24/),
     & TMP, W, AMP(1,4))
      CALL FFV1P1N_2(W(1,65), W(1,52), GC_2, TMP(1))
      call CombineAmp(7,
     & (/83,79,81,75,70,77,73/), 
     & (/17,18,20,21,22,23,24/),
     & TMP, W, AMP(1,4))
      CALL FFV1P1N_2(W(1,65), W(1,53), GC_2, TMP(1))
      call CombineAmp(8,
     & (/132,128,134,130,124,119,126,122/), 
     & (/17,18,19,20,21,22,23,24/),
     & TMP, W, AMP(1,4))
      CALL FFV1P1N_2(W(1,65), W(1,54), GC_2, TMP(1))
      call CombineAmp(8,
     & (/98,94,100,96,90,85,92,88/), 
     & (/17,18,19,20,21,22,23,24/),
     & TMP, W, AMP(1,4))
      CALL FFV1P1N_2(W(1,66), W(1,51), GC_2, TMP(1))
      call CombineAmp(8,
     & (/50,46,52,48,42,36,44,39/), 
     & (/17,18,19,20,21,22,23,24/),
     & TMP, W, AMP(1,4))
      CALL FFV1P1N_2(W(1,66), W(1,52), GC_2, TMP(1))
      call CombineAmp(8,
     & (/14,10,16,12,6,1,8,4/), 
     & (/17,18,19,20,21,22,23,24/),
     & TMP, W, AMP(1,4))
      CALL FFV1P1N_2(W(1,66), W(1,53), GC_2, TMP(1))
      call CombineAmp(8,
     & (/67,63,69,65,59,54,61,57/), 
     & (/17,18,19,20,21,22,23,24/),
     & TMP, W, AMP(1,4))
      CALL FFV1P1N_2(W(1,66), W(1,54), GC_2, TMP(1))
      call CombineAmp(8,
     & (/32,28,34,30,24,18,26,21/), 
     & (/17,18,19,20,21,22,23,24/),
     & TMP, W, AMP(1,4))
      CALL FFV1P1N_2(W(1,67), W(1,51), GC_2, TMP(1))
      call CombineAmp(8,
     & (/116,112,118,114,108,103,110,106/), 
     & (/17,18,19,20,21,22,23,24/),
     & TMP, W, AMP(1,4))
      CALL FFV1P1N_2(W(1,67), W(1,52), GC_2, TMP(1))
      call CombineAmp(7,
     & (/84,80,82,76,72,78,74/), 
     & (/17,18,20,21,22,23,24/),
     & TMP, W, AMP(1,4))
      CALL FFV1P1N_2(W(1,67), W(1,53), GC_2, TMP(1))
      call CombineAmp(8,
     & (/133,129,135,131,125,121,127,123/), 
     & (/17,18,19,20,21,22,23,24/),
     & TMP, W, AMP(1,4))
      CALL FFV1P1N_2(W(1,67), W(1,54), GC_2, TMP(1))
      call CombineAmp(7,
     & (/99,95,97,91,87,93,89/), 
     & (/17,18,20,21,22,23,24/),
     & TMP, W, AMP(1,4))
      CALL FFV1P1N_2(W(1,68), W(1,51), GC_2, TMP(1))
      call CombineAmp(8,
     & (/51,47,53,49,43,38,45,41/), 
     & (/17,18,19,20,21,22,23,24/),
     & TMP, W, AMP(1,4))
      CALL FFV1P1N_2(W(1,68), W(1,52), GC_2, TMP(1))
      call CombineAmp(8,
     & (/15,11,17,13,7,3,9,5/), 
     & (/17,18,19,20,21,22,23,24/),
     & TMP, W, AMP(1,4))
      CALL FFV1P1N_2(W(1,68), W(1,53), GC_2, TMP(1))
      call CombineAmp(7,
     & (/68,64,66,60,56,62,58/), 
     & (/17,18,20,21,22,23,24/),
     & TMP, W, AMP(1,4))
      CALL FFV1P1N_2(W(1,68), W(1,54), GC_2, TMP(1))
      call CombineAmp(8,
     & (/33,29,35,31,25,20,27,23/), 
     & (/17,18,19,20,21,22,23,24/),
     & TMP, W, AMP(1,4))  !  count 1
      CALL FFS4P1N_2(W(1,63), W(1,55), GC_94, TMP(1))
      call CombineAmp(2,
     & (/102,105/), 
     & (/22,24/),
     & TMP, W, AMP(1,5))
      CALL FFS4_0(W(1,63),W(1,22),W(1,56),GC_94,AMP(71,5))
      CALL FFS4_0(W(1,63),W(1,22),W(1,57),GC_94,AMP(120,5))
      CALL FFS4_0(W(1,63),W(1,22),W(1,58),GC_94,AMP(86,5))
      CALL FFS4P1N_2(W(1,64), W(1,55), GC_94, TMP(1))
      call CombineAmp(2,
     & (/37,40/), 
     & (/22,24/),
     & TMP, W, AMP(1,5))
      CALL FFS4_0(W(1,64),W(1,22),W(1,56),GC_94,AMP(2,5))
      CALL FFS4_0(W(1,64),W(1,22),W(1,57),GC_94,AMP(55,5))
      CALL FFS4P1N_2(W(1,64), W(1,58), GC_94, TMP(1))
      call CombineAmp(2,
     & (/19,22/), 
     & (/22,24/),
     & TMP, W, AMP(1,5))
      CALL FFS4P1N_2(W(1,65), W(1,55), GC_94, TMP(1))
      call CombineAmp(8,
     & (/115,111,117,113,107,101,109,104/), 
     & (/17,18,19,20,21,22,23,24/),
     & TMP, W, AMP(1,5))
      CALL FFS4P1N_2(W(1,65), W(1,56), GC_94, TMP(1))
      call CombineAmp(7,
     & (/83,79,81,75,70,77,73/), 
     & (/17,18,20,21,22,23,24/),
     & TMP, W, AMP(1,5))
      CALL FFS4P1N_2(W(1,65), W(1,57), GC_94, TMP(1))
      call CombineAmp(8,
     & (/132,128,134,130,124,119,126,122/), 
     & (/17,18,19,20,21,22,23,24/),
     & TMP, W, AMP(1,5))
      CALL FFS4P1N_2(W(1,65), W(1,58), GC_94, TMP(1))
      call CombineAmp(8,
     & (/98,94,100,96,90,85,92,88/), 
     & (/17,18,19,20,21,22,23,24/),
     & TMP, W, AMP(1,5))
      CALL FFS4P1N_2(W(1,66), W(1,55), GC_94, TMP(1))
      call CombineAmp(8,
     & (/50,46,52,48,42,36,44,39/), 
     & (/17,18,19,20,21,22,23,24/),
     & TMP, W, AMP(1,5))
      CALL FFS4P1N_2(W(1,66), W(1,56), GC_94, TMP(1))
      call CombineAmp(8,
     & (/14,10,16,12,6,1,8,4/), 
     & (/17,18,19,20,21,22,23,24/),
     & TMP, W, AMP(1,5))
      CALL FFS4P1N_2(W(1,66), W(1,57), GC_94, TMP(1))
      call CombineAmp(8,
     & (/67,63,69,65,59,54,61,57/), 
     & (/17,18,19,20,21,22,23,24/),
     & TMP, W, AMP(1,5))
      CALL FFS4P1N_2(W(1,66), W(1,58), GC_94, TMP(1))
      call CombineAmp(8,
     & (/32,28,34,30,24,18,26,21/), 
     & (/17,18,19,20,21,22,23,24/),
     & TMP, W, AMP(1,5))
      CALL FFS4P1N_2(W(1,67), W(1,55), GC_94, TMP(1))
      call CombineAmp(8,
     & (/116,112,118,114,108,103,110,106/), 
     & (/17,18,19,20,21,22,23,24/),
     & TMP, W, AMP(1,5))
      CALL FFS4P1N_2(W(1,67), W(1,56), GC_94, TMP(1))
      call CombineAmp(7,
     & (/84,80,82,76,72,78,74/), 
     & (/17,18,20,21,22,23,24/),
     & TMP, W, AMP(1,5))
      CALL FFS4P1N_2(W(1,67), W(1,57), GC_94, TMP(1))
      call CombineAmp(8,
     & (/133,129,135,131,125,121,127,123/), 
     & (/17,18,19,20,21,22,23,24/),
     & TMP, W, AMP(1,5))
      CALL FFS4P1N_2(W(1,67), W(1,58), GC_94, TMP(1))
      call CombineAmp(7,
     & (/99,95,97,91,87,93,89/), 
     & (/17,18,20,21,22,23,24/),
     & TMP, W, AMP(1,5))
      CALL FFS4P1N_2(W(1,68), W(1,55), GC_94, TMP(1))
      call CombineAmp(8,
     & (/51,47,53,49,43,38,45,41/), 
     & (/17,18,19,20,21,22,23,24/),
     & TMP, W, AMP(1,5))
      CALL FFS4P1N_2(W(1,68), W(1,56), GC_94, TMP(1))
      call CombineAmp(8,
     & (/15,11,17,13,7,3,9,5/), 
     & (/17,18,19,20,21,22,23,24/),
     & TMP, W, AMP(1,5))
      CALL FFS4P1N_2(W(1,68), W(1,57), GC_94, TMP(1))
      call CombineAmp(7,
     & (/68,64,66,60,56,62,58/), 
     & (/17,18,20,21,22,23,24/),
     & TMP, W, AMP(1,5))
      CALL FFS4P1N_2(W(1,68), W(1,58), GC_94, TMP(1))
      call CombineAmp(8,
     & (/33,29,35,31,25,20,27,23/), 
     & (/17,18,19,20,21,22,23,24/),
     & TMP, W, AMP(1,5))  !  count 1
      CALL FFV2_5P1N_2(W(1,63), W(1,59), GC_51, GC_58, TMP(1))
      call CombineAmp(2,
     & (/102,105/), 
     & (/22,24/),
     & TMP, W, AMP(1,6))
      CALL FFV2_5_0(W(1,63),W(1,22),W(1,60),GC_51,GC_58,AMP(71,6))
      CALL FFV2_5_0(W(1,63),W(1,22),W(1,61),GC_51,GC_58,AMP(120,6))
      CALL FFV2_5_0(W(1,63),W(1,22),W(1,62),GC_51,GC_58,AMP(86,6))
      CALL FFV2_5P1N_2(W(1,64), W(1,59), GC_51, GC_58, TMP(1))
      call CombineAmp(2,
     & (/37,40/), 
     & (/22,24/),
     & TMP, W, AMP(1,6))
      CALL FFV2_5_0(W(1,64),W(1,22),W(1,60),GC_51,GC_58,AMP(2,6))
      CALL FFV2_5_0(W(1,64),W(1,22),W(1,61),GC_51,GC_58,AMP(55,6))
      CALL FFV2_5P1N_2(W(1,64), W(1,62), GC_51, GC_58, TMP(1))
      call CombineAmp(2,
     & (/19,22/), 
     & (/22,24/),
     & TMP, W, AMP(1,6))
      CALL FFV2_5P1N_2(W(1,65), W(1,59), GC_51, GC_58, TMP(1))
      call CombineAmp(8,
     & (/115,111,117,113,107,101,109,104/), 
     & (/17,18,19,20,21,22,23,24/),
     & TMP, W, AMP(1,6))
      CALL FFV2_5P1N_2(W(1,65), W(1,60), GC_51, GC_58, TMP(1))
      call CombineAmp(7,
     & (/83,79,81,75,70,77,73/), 
     & (/17,18,20,21,22,23,24/),
     & TMP, W, AMP(1,6))
      CALL FFV2_5P1N_2(W(1,65), W(1,61), GC_51, GC_58, TMP(1))
      call CombineAmp(8,
     & (/132,128,134,130,124,119,126,122/), 
     & (/17,18,19,20,21,22,23,24/),
     & TMP, W, AMP(1,6))
      CALL FFV2_5P1N_2(W(1,65), W(1,62), GC_51, GC_58, TMP(1))
      call CombineAmp(8,
     & (/98,94,100,96,90,85,92,88/), 
     & (/17,18,19,20,21,22,23,24/),
     & TMP, W, AMP(1,6))
      CALL FFV2_5P1N_2(W(1,66), W(1,59), GC_51, GC_58, TMP(1))
      call CombineAmp(8,
     & (/50,46,52,48,42,36,44,39/), 
     & (/17,18,19,20,21,22,23,24/),
     & TMP, W, AMP(1,6))
      CALL FFV2_5P1N_2(W(1,66), W(1,60), GC_51, GC_58, TMP(1))
      call CombineAmp(8,
     & (/14,10,16,12,6,1,8,4/), 
     & (/17,18,19,20,21,22,23,24/),
     & TMP, W, AMP(1,6))
      CALL FFV2_5P1N_2(W(1,66), W(1,61), GC_51, GC_58, TMP(1))
      call CombineAmp(8,
     & (/67,63,69,65,59,54,61,57/), 
     & (/17,18,19,20,21,22,23,24/),
     & TMP, W, AMP(1,6))
      CALL FFV2_5P1N_2(W(1,66), W(1,62), GC_51, GC_58, TMP(1))
      call CombineAmp(8,
     & (/32,28,34,30,24,18,26,21/), 
     & (/17,18,19,20,21,22,23,24/),
     & TMP, W, AMP(1,6))
      CALL FFV2_5P1N_2(W(1,67), W(1,59), GC_51, GC_58, TMP(1))
      call CombineAmp(8,
     & (/116,112,118,114,108,103,110,106/), 
     & (/17,18,19,20,21,22,23,24/),
     & TMP, W, AMP(1,6))
      CALL FFV2_5P1N_2(W(1,67), W(1,60), GC_51, GC_58, TMP(1))
      call CombineAmp(7,
     & (/84,80,82,76,72,78,74/), 
     & (/17,18,20,21,22,23,24/),
     & TMP, W, AMP(1,6))
      CALL FFV2_5P1N_2(W(1,67), W(1,61), GC_51, GC_58, TMP(1))
      call CombineAmp(8,
     & (/133,129,135,131,125,121,127,123/), 
     & (/17,18,19,20,21,22,23,24/),
     & TMP, W, AMP(1,6))
      CALL FFV2_5P1N_2(W(1,67), W(1,62), GC_51, GC_58, TMP(1))
      call CombineAmp(7,
     & (/99,95,97,91,87,93,89/), 
     & (/17,18,20,21,22,23,24/),
     & TMP, W, AMP(1,6))
      CALL FFV2_5P1N_2(W(1,68), W(1,59), GC_51, GC_58, TMP(1))
      call CombineAmp(8,
     & (/51,47,53,49,43,38,45,41/), 
     & (/17,18,19,20,21,22,23,24/),
     & TMP, W, AMP(1,6))
      CALL FFV2_5P1N_2(W(1,68), W(1,60), GC_51, GC_58, TMP(1))
      call CombineAmp(8,
     & (/15,11,17,13,7,3,9,5/), 
     & (/17,18,19,20,21,22,23,24/),
     & TMP, W, AMP(1,6))
      CALL FFV2_5P1N_2(W(1,68), W(1,61), GC_51, GC_58, TMP(1))
      call CombineAmp(7,
     & (/68,64,66,60,56,62,58/), 
     & (/17,18,20,21,22,23,24/),
     & TMP, W, AMP(1,6))
      CALL FFV2_5P1N_2(W(1,68), W(1,62), GC_51, GC_58, TMP(1))
      call CombineAmp(8,
     & (/33,29,35,31,25,20,27,23/), 
     & (/17,18,19,20,21,22,23,24/),
     & TMP, W, AMP(1,6))  !  count 1

      JAMP(:,:)  = (0d0,0d0)
      DO K = 1, NCOMB
        
        JAMP(:,:) = (0D0,0D0)
C       JAMPs contributing to orders ALL_ORDERS=1
        JAMP(1,1) = AMP( K,1)+AMP( K,2)+AMP( K,3)+AMP( K,4)+AMP( K,5)+AM
     $  P( K,6)

        TS(K) = 0.D0 
        DO M = 1, NAMPSO
          CF_INDEX = 0
          DO I = 1, NCOLOR
            ZTEMP = (0.D0,0.D0)
            DO J = I, NCOLOR
              CF_INDEX = CF_INDEX + 1
              ZTEMP = ZTEMP + CF(CF_INDEX)*JAMP(J,M)
            ENDDO    !  J
            DO N = 1, NAMPSO

              TS(K) = TS(K) + REAL(ZTEMP*DCONJG(JAMP(I,N)))

            ENDDO    !  N
          ENDDO    !  I
        ENDDO    !  M
        TS(K) = TS(K) / DENOM
        if(sde_strat.eq.1) then
        
        IF(SDE_STRAT.EQ.1)THEN
          AMP2(1)=AMP2(1)+(AMP( K,1)+AMP( K,2)+AMP( K,3))*DCONJG(AMP( K,
     $    1)+AMP( K,2)   +AMP( K,3))
          AMP2(4)=AMP2(4)+(AMP( K,4)+AMP( K,5)+AMP( K,6))*DCONJG(AMP( K,
     $    4)+AMP( K,5)   +AMP( K,6))
        ENDIF

        endif
        Do I = 1, NCOLOR
          DO M = 1, NAMPSO
            DO N = 1, NAMPSO

              Jamp2(i)=Jamp2(i)+DABS(DBLE(Jamp(i,m)*dconjg(Jamp(i,n))))

            enddo
          enddo
        Enddo
      ENDDO    !  K

      END


      SUBROUTINE PRINT_ZERO_AMP_1()

      integer i
      i =1
      return
      end

C     Set of functions to handle the array indices of the split orders


      INTEGER FUNCTION SQSOINDEX1(ORDERINDEXA, ORDERINDEXB)
C     
C     This functions plays the role of the interference matrix. It can
C      be hardcoded or 
C     made more elegant using hashtables if its execution speed ever
C      becomes a relevant
C     factor. From two split order indices, it return the
C      corresponding index in the squared 
C     order canonical ordering.
C     
C     CONSTANTS
C     

      INTEGER    NSO, NSQUAREDSO, NAMPSO
      PARAMETER (NSO=1, NSQUAREDSO=1, NAMPSO=1)
C     
C     ARGUMENTS
C     
      INTEGER ORDERINDEXA, ORDERINDEXB
C     
C     LOCAL VARIABLES
C     
      INTEGER I, SQORDERS(NSO)
      INTEGER AMPSPLITORDERS(NAMPSO,NSO)
      DATA (AMPSPLITORDERS(  1,i),i=  1,  1) /    1/
      COMMON/AMPSPLITORDERS1/AMPSPLITORDERS
C     
C     FUNCTION
C     
      INTEGER SOINDEX_FOR_SQUARED_ORDERS1
C     
C     BEGIN CODE
C     
      DO I=1,NSO
        SQORDERS(I)=AMPSPLITORDERS(ORDERINDEXA,I)
     $   +AMPSPLITORDERS(ORDERINDEXB,I)
      ENDDO
      SQSOINDEX1=SOINDEX_FOR_SQUARED_ORDERS1(SQORDERS)
      END

      INTEGER FUNCTION SOINDEX_FOR_SQUARED_ORDERS1(ORDERS)
C     
C     This functions returns the integer index identifying the squared
C      split orders list passed in argument which corresponds to the
C      values of the following list of couplings (and in this order).
C     []
C     
C     CONSTANTS
C     
      INTEGER    NSO, NSQSO, NAMPSO
      PARAMETER (NSO=1, NSQSO=1, NAMPSO=1)
C     
C     ARGUMENTS
C     
      INTEGER ORDERS(NSO)
C     
C     LOCAL VARIABLES
C     
      INTEGER I,J
      INTEGER SQSPLITORDERS(NSQSO,NSO)
      DATA (SQSPLITORDERS(  1,i),i=  1,  1) /    2/
      COMMON/SQPLITORDERS1/SQPLITORDERS
C     
C     BEGIN CODE
C     
      DO I=1,NSQSO
        DO J=1,NSO
          IF (ORDERS(J).NE.SQSPLITORDERS(I,J)) GOTO 1009
        ENDDO
        SOINDEX_FOR_SQUARED_ORDERS1 = I
        RETURN
 1009   CONTINUE
      ENDDO

      WRITE(*,*) 'ERROR:: Stopping in function' 
      WRITE(*,*) 'SOINDEX_FOR_SQUARED_ORDERS1'
      WRITE(*,*) 'Could not find squared orders ',(ORDERS(I),I=1,NSO)
      STOP

      END

      SUBROUTINE GET_NSQSO_BORN1(NSQSO)
C     
C     Simple subroutine returning the number of squared split order
C     contributions returned when calling smatrix_split_orders 
C     

      INTEGER    NSQUAREDSO
      PARAMETER  (NSQUAREDSO=1)

      INTEGER NSQSO

      NSQSO=NSQUAREDSO

      END

C     This is the inverse subroutine of SOINDEX_FOR_SQUARED_ORDERS.
C      Not directly useful, but provided nonetheless.
      SUBROUTINE GET_SQUARED_ORDERS_FOR_SOINDEX1(SOINDEX,ORDERS)
C     
C     This functions returns the orders identified by the squared
C      split order index in argument. Order values correspond to
C      following list of couplings (and in this order):
C     []
C     
C     CONSTANTS
C     
      INTEGER    NSO, NSQSO
      PARAMETER (NSO=1, NSQSO=1)
C     
C     ARGUMENTS
C     
      INTEGER SOINDEX, ORDERS(NSO)
C     
C     LOCAL VARIABLES
C     
      INTEGER I
      INTEGER SQPLITORDERS(NSQSO,NSO)
      COMMON/SQPLITORDERS1/SQPLITORDERS	  
C     
C     BEGIN CODE
C     
      IF (SOINDEX.gt.0.and.SOINDEX.le.NSQSO) THEN
        DO I=1,NSO
          ORDERS(I) =  SQPLITORDERS(SOINDEX,I)
        ENDDO
        RETURN
      ENDIF

      WRITE(*,*) 'ERROR:: Stopping function'
     $ //' GET_SQUARED_ORDERS_FOR_SOINDEX1'
      WRITE(*,*) 'Could not find squared orders index ',SOINDEX
      STOP

      END SUBROUTINE

C     This is the inverse subroutine of getting amplitude SO orders.
C      Not directly useful, but provided nonetheless.
      SUBROUTINE GET_ORDERS_FOR_AMPSOINDEX1(SOINDEX,ORDERS)
C     
C     This functions returns the orders identified by the split order
C      index in argument. Order values correspond to following list of
C      couplings (and in this order):
C     []
C     
C     CONSTANTS
C     
      INTEGER    NSO, NAMPSO
      PARAMETER (NSO=1, NAMPSO=1)
C     
C     ARGUMENTS
C     
      INTEGER SOINDEX, ORDERS(NSO)
C     
C     LOCAL VARIABLES
C     
      INTEGER I
      INTEGER AMPSPLITORDERS(NAMPSO,NSO)
      COMMON/AMPSPLITORDERS1/AMPSPLITORDERS
C     
C     BEGIN CODE
C     
      IF (SOINDEX.gt.0.and.SOINDEX.le.NAMPSO) THEN
        DO I=1,NSO
          ORDERS(I) =  AMPSPLITORDERS(SOINDEX,I)
        ENDDO
        RETURN
      ENDIF

      WRITE(*,*) 'ERROR:: Stopping function GET_ORDERS_FOR_AMPSOINDEX1'
      WRITE(*,*) 'Could not find amplitude split orders index ',SOINDEX
      STOP

      END SUBROUTINE

C     This function is not directly useful, but included for
C      completeness
      INTEGER FUNCTION SOINDEX_FOR_AMPORDERS1(ORDERS)
C     
C     This functions returns the integer index identifying the
C      amplitude split orders passed in argument which correspond to
C      the values of the following list of couplings (and in this
C      order):
C     []
C     
C     CONSTANTS
C     
      INTEGER    NSO, NAMPSO
      PARAMETER (NSO=1, NAMPSO=1)
C     
C     ARGUMENTS
C     
      INTEGER ORDERS(NSO)
C     
C     LOCAL VARIABLES
C     
      INTEGER I,J
      INTEGER AMPSPLITORDERS(NAMPSO,NSO)
      COMMON/AMPSPLITORDERS1/AMPSPLITORDERS
C     
C     BEGIN CODE
C     
      DO I=1,NAMPSO
        DO J=1,NSO
          IF (ORDERS(J).NE.AMPSPLITORDERS(I,J)) GOTO 1009
        ENDDO
        SOINDEX_FOR_AMPORDERS1 = I
        RETURN
 1009   CONTINUE
      ENDDO

      WRITE(*,*) 'ERROR:: Stopping function SOINDEX_FOR_AMPORDERS1'
      WRITE(*,*) 'Could not find squared orders ',(ORDERS(I),I=1,NSO)
      STOP

      END

