ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of sm-full'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_11 = ', GC_11
      WRITE(*,2) 'GC_2 = ', GC_2
      WRITE(*,2) 'GC_3 = ', GC_3
      WRITE(*,2) 'GC_40 = ', GC_40
      WRITE(*,2) 'GC_41 = ', GC_41
      WRITE(*,2) 'GC_42 = ', GC_42
      WRITE(*,2) 'GC_43 = ', GC_43
      WRITE(*,2) 'GC_44 = ', GC_44
      WRITE(*,2) 'GC_45 = ', GC_45
      WRITE(*,2) 'GC_46 = ', GC_46
      WRITE(*,2) 'GC_49 = ', GC_49
      WRITE(*,2) 'GC_50 = ', GC_50
      WRITE(*,2) 'GC_51 = ', GC_51
      WRITE(*,2) 'GC_58 = ', GC_58
      WRITE(*,2) 'GC_59 = ', GC_59
      WRITE(*,2) 'GC_93 = ', GC_93
      WRITE(*,2) 'GC_94 = ', GC_94
      WRITE(*,2) 'GC_100 = ', GC_100
      WRITE(*,2) 'GC_101 = ', GC_101
      WRITE(*,2) 'GC_102 = ', GC_102
      WRITE(*,2) 'GC_103 = ', GC_103
      WRITE(*,2) 'GC_104 = ', GC_104
      WRITE(*,2) 'GC_105 = ', GC_105
      WRITE(*,2) 'GC_108 = ', GC_108
